### ISSUE TITLE
Atom >=1.2: "Error: Could not find module root given file: "undefined". Do you have a `package.json` file? "

### ISSUE THREAD

**Issue by gnestor** [jupyter/atom-notebook#10]
[Enter steps to reproduce below:]

1. Clone atom-notebook
2. `apm install`
3. `apm link`
4. Run Atom >=1.2

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: [jupyter-notebook](https://github.com/willwhitney/jupyter-notebook-atom) package, v0.0.1

### Stack Trace

Failed to load the jupyter-notebook package

```
At Could not find module root given file: "undefined". Do you have a `package.json` file? 

Error: Could not find module root given file: "undefined". Do you have a `package.json` file? 
    at Function.getRoot (/Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/node_modules/bindings/bindings.js:159:13)
    at bindings (/Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/node_modules/bindings/bindings.js:55:32)
    at Object.<anonymous> (/Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/index.js:2:18)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "native-ui",
      "atom-toychest"
    ],
    "disabledPackages": [
      "RubyMotion",
      "atom-ternjs",
      "preview",
      "SFTP-deployment",
      "language-haml"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Stylus, v1.2.1
api-workbench, v0.8.6
atom-toychest, v0.3.0
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
file-icons, v1.6.12
jupyter-notebook, v0.0.1
language-ejs, v0.2.0
language-gradle, v0.0.3
language-jade, v0.6.2
linter, v1.11.2
linter-eslint, v5.2.1
linter-htmlhint, v0.2.1
linter-sass-lint, v0.4.1
native-ui, v0.9.0
open-recent, v4.0.1
pigments, v0.19.0
pretty-json, v0.4.1
react, v0.12.10
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by gnestor** [comment]
This is an issue with Atom >=1.2 and zmq (which depends on bindings). According to @n-riesco:

* The problem is not really in zmq but in bindings.
* My understanding is that bindings is a requirement for any packages using native modules.
* This issue is caused by Atom v1.2.0 making Error.prepareStackTrace read-only (see commit c36b4bd )
* bindings needs to know the path to the filename that has invoked bindings. This information is only available in the stack trace, hence the need to use Error.prepareStackTrace (see details in https://github.com/TooTallNate/node-bindings/blob/master/bindings.js#L102 )

Related issues:
https://github.com/atom/atom/issues/9660#event-467429815
https://github.com/JustinTulloss/zeromq.node/issues/466
https://github.com/willwhitney/hydrogen/issues/135

**Comment by gnestor** [comment]
Fixed by https://github.com/jupyter/atom-notebook/pull/11
