### ISSUE TITLE
Jupyter-notebook fails to install in ATOM

### ISSUE THREAD

**Issue by OrbitalMechanic** [jupyter/atom-notebook#100]
I'm attempting to install the Jupyter-notebook in ATOM (version 1.45.0). ATOM is running on a Mac Pro (2019) under Mac OS X ver. 10.15.4 (Catalina). The output from the attempted installation follows.

Installing package jupyter-notebook failed Error: Installing “jupyter-notebook@0.0.10” failed.
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:942369
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:936821)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125033)
    at t.bufferStream (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125187)
    at Socket.e.on (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1123789)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12) 
> bufferutil@1.2.1 install /private/var/folders/2r/4bw6nw0x58z0_ybx632_h14m0000gq/T/apm-install-dir-120315-55677-1pt292a.oo7b/node_modules/jupyter-notebook/node_modules/bufferutil
> node-gyp rebuild

> utf-8-validate@1.2.2 install /private/var/folders/2r/4bw6nw0x58z0_ybx632_h14m0000gq/T/apm-install-dir-120315-55677-1pt292a.oo7b/node_modules/jupyter-notebook/node_modules/utf-8-validate
> node-gyp rebuild

> pathwatcher@8.1.0 install /private/var/folders/2r/4bw6nw0x58z0_ybx632_h14m0000gq/T/apm-install-dir-120315-55677-1pt292a.oo7b/node_modules/jupyter-notebook/node_modules/pathwatcher
> node-gyp rebuild

npm WARN deprecated jupyter-js-services@0.21.1: This package has moved to @jupyterlab/services
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.6, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:596:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/2r/4bw6nw0x58z0_ybx632_h14m0000gq/T/apm-install-dir-120315-55677-1pt292a.oo7b/node_modules/jupyter-notebook/node_modules/bufferutil
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.6, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:596:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/2r/4bw6nw0x58z0_ybx632_h14m0000gq/T/apm-install-dir-120315-55677-1pt292a.oo7b/node_modules/jupyter-notebook/node_modules/utf-8-validate
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.6, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:596:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/2r/4bw6nw0x58z0_ybx632_h14m0000gq/T/apm-install-dir-120315-55677-1pt292a.oo7b/node_modules/jupyter-notebook/node_modules/pathwatcher
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/2r/4bw6nw0x58z0_ybx632_h14m0000gq/T/apm-install-dir-120315-55677-1pt292a.oo7b/package.json'
npm WARN apm-install-dir-120315-55677-1pt292a.oo7b No description
npm WARN apm-install-dir-120315-55677-1pt292a.oo7b No repository field.
npm WARN apm-install-dir-120315-55677-1pt292a.oo7b No README data
npm WARN apm-install-dir-120315-55677-1pt292a.oo7b No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules/jupyter-notebook/node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules/jupyter-notebook/node_modules/utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pathwatcher@8.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher@8.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.atom/.apm/_logs/2020-04-16T01_51_30_318Z-debug.log

Please advise.
Sam Dupree.

**Comment by ogola89** [comment]
I have the same issue. It seems it begins with the python interpreter not being the recommended (>= v2.5.0 & < 3.0.0.) but Python 2.7 is now out of use?
