### ISSUE TITLE
Failed to load the jupyter-notebook package

### ISSUE THREAD

**Issue by fmaschietto** [jupyter/atom-notebook#102]
/Users/federica/.atom/packages/jupyter-notebook/lib/main.js: Unexpected token (36:4)
Hide Stack Trace
SyntaxError: /Users/federica/.atom/packages/jupyter-notebook/lib/main.js: Unexpected token (36:4)
        return el;
      }
    });
  },
  deactivate() {
    at Parser.pp.raise (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.expect (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/util.js:76:33)
    at Parser.pp.parseExprList (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:785:12)
    at Parser.pp.parseSubscripts (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:270:29)
    at Parser.pp.parseExprSubscripts (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:240:17)
    at Parser.pp.parseMaybeUnary (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExpression (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:79:19)
    at Parser.pp.parseStatement (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/statement.js:137:23)
    at Parser.parseStatement (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseBlock (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/statement.js:442:21)
    at Parser.pp.parseFunctionBody (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:747:22)
    at Parser.parseFunctionBody (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/plugins/flow.js:643:20)
    at Parser.pp.parseMethod (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:717:8)
    at Parser.pp.parseObjPropValue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:658:23)
    at Parser.parseObjPropValue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/plugins/flow.js:891:13)
    at Parser.pp.parseObj (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:640:10)
    at Parser.pp.parseExprAtom (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:392:19)
    at Parser.parseExprAtom (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExport (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/statement.js:682:21)
    at Parser.parseExport (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/plugins/flow.js:713:20)
    at Parser.pp.parseStatement (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/statement.js:115:90)
    at Parser.parseStatement (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseTopLevel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/statement.js:30:21)
    at Parser.parse (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/index.js:70:17)
    at Object.parse (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/index.js:45:50)
    at Object.exports.default (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/helpers/parse.js:36:18)
    at File.parse (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/transformation/file/index.js:574:40)
    at File.parseCode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/transformation/file/index.js:691:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/transformation/pipeline.js:167:12
    at File.wrap (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/transformation/file/index.js:639:16)
    at Pipeline.transform (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
    at Object.e.compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:577655)
    at Object.compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:574454)
    at compileFileAtPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:148545)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150943)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3197086)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3183626)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3182458)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3183199)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381274)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:380002)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382574)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:943557
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:938163)
    at o (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1122261)
    at ChildProcess.n.process.on.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1122467)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)### ###

**Comment by MTR7** [comment]
Hello ,

I get the same is there any solution for this Issue

**Comment by samusz** [comment]
same here

**Comment by Amazeryogo** [comment]
Same Here. I too have macOS Catalina 10.15.4 and it showed an error

**Comment by LeonardoPaccianiMori** [comment]
Same here. I have pop!_OS 20.04, atom 1.45.0 and jupyter-notebook 0.0.10

**Comment by yalin** [comment]
I explained here how to solve it: https://github.com/jupyter/atom-notebook/issues/104#issuecomment-641316449

There is a wrong bracket "}" committed.
