### ISSUE TITLE
Failed to load the jupyter-notebook package

### ISSUE THREAD

**Issue by 16007005** [jupyter/atom-notebook#104]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [jupyter-notebook](https://github.com/jupyter/atom-notebook) package 0.0.10

### Stack Trace

Failed to load the jupyter-notebook package

```
At Cannot find module 'react'
Require stack:
- C:\Users\Administrator\.atom\packages\atom-notebook\lib\main.js
- C:\Users\Administrator\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html

Error: Cannot find module 'react'
Require stack:
- C:\Users\Administrator\.atom\packages\atom-notebook\lib\main.js
- C:\Users\Administrator\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /packages/atom-notebook/lib/main.js:7:14)
    at /packages/atom-notebook/lib/main.js:90:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:1:735013)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3310163)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3296703
    at Package.measure (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3295535)
    at Package.load (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3296276)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:381312)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:379735
    at Config.transact (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:331800)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:379673)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:1:755624
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:1:757663)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
jupyter-notebook 0.0.10 
atom-python-run 0.9.7 
data-atom 0.29.1 
ide-python 1.5.0 
process-palette 0.17.0 
script 3.25.0 
teletype 0.13.4 
```

**Comment by Amazeryogo** [comment]
I had given the same issue some days ago. Can somebody please help us?

**Comment by Amazeryogo** [comment]
yntaxError: /Users/user/.atom/packages/jupyter-notebook/lib/main.js: Unexpected token (36:4)
        return el;
      }
    });
  },
  deactivate() {
    at Parser.pp.raise (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.expect (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/util.js:76:33)
    at Parser.pp.parseExprList (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:785:12)
    at Parser.pp.parseSubscripts (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:270:29)
    at Parser.pp.parseExprSubscripts (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:240:17)
    at Parser.pp.parseMaybeUnary (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExpression (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:79:19)
    at Parser.pp.parseStatement (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/statement.js:137:23)
    at Parser.parseStatement (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseBlock (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/statement.js:442:21)
    at Parser.pp.parseFunctionBody (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:747:22)
    at Parser.parseFunctionBody (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/plugins/flow.js:643:20)
    at Parser.pp.parseMethod (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:717:8)
    at Parser.pp.parseObjPropValue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:658:23)
    at Parser.parseObjPropValue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/plugins/flow.js:891:13)
    at Parser.pp.parseObj (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:640:10)
    at Parser.pp.parseExprAtom (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:392:19)
    at Parser.parseExprAtom (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExport (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/statement.js:682:21)
    at Parser.parseExport (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/plugins/flow.js:713:20)
    at Parser.pp.parseStatement (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babylon/lib/parser/statement.js:115:90)

**Comment by jakewilliami** [comment]
I'm getting the same error on macOS 10.14.6, running Atom version 1.46.0.  Non-core packages are:
```
hydrogen 2.14.1
aligner-lua 1.0.1
atom-julia-run 1.0.5
atom-language-r 1.4.8
busy-signal 2.0.1
graphviz-preview-plus 1.5.10
hydrogen-launcher 1.2.2
hyperclick 0.1.5
ide-r 0.1.8
indent-detective 0.4.0
ink 0.12.4
intentions 1.1.5
julia-client 0.12.5
juno-plus 0.12.2
jupyter-notebook 0.0.10
language-asymptote 1.1.0
language-dot 1.7.0
language-julia 0.19.3
language-lisp 0.2.0
language-lua 0.9.11
language-metapost 0.0.2
latex-completions 0.3.6
linter 2.3.1
linter-julia 0.8.3
linter-ui-default 1.8.1
platformio-die-terminal 2.10.0
r-exec 0.5.0
tool-bar 1.3.0
uber-juno 0.3.0
```

**Comment by Amazeryogo** [comment]
I too use MacOS 10.14.6

**Comment by yalin** [comment]
I guess this is solved, basically a wrong bracket issue. You can fix urself as well. Issue: #67

**Comment by Amazeryogo** [comment]
@yalin  Which one is solved?

**Comment by yalin** [comment]
> @yalin Which one is solved?

@Amazeryogo ; There is a mistaken bracket in the file main.js

quote from your post; 
> yntaxError: **/Users/user/.atom/packages/jupyter-notebook/lib/main.js**: Unexpected token (36:4)
> return el;
> }
> });
> },
> deactivate() {

Simply delete the one of the bracket "}" after "return el;" and save the file. 
Either "}" alone or "}" before ");"

So it should look like;
> return el;
>    }
> );
> },
> deactivate() {

**Comment by Amazeryogo** [comment]
@yalin  oh ok Thanks!

**Comment by 22vatsu** [comment]
how to write in that block ....we can't change that code

**Comment by Charlie5DH** [comment]
have the same issue, hoe can i modify that file to delete the bracket?

**Comment by apw024** [comment]
> have the same issue, hoe can i modify that file to delete the bracket?

open the file in atom then edit and save it??

**Comment by aaronfoe** [comment]
I tried @yalin 's fix, and I can now open notebooks inside atom, but they are incorrectly displayed. Here's a screenshot of what it looks like for me ( Atom v.1.49, MacOS 10.13.4): 
<img width="981" alt="delete" src="https://user-images.githubusercontent.com/61985120/88183010-31409000-cc31-11ea-9817-7b14514d6082.png">

**Comment by apophenist** [comment]
> I tried @yalin 's fix, and I can now open notebooks inside atom, but they are incorrectly displayed. Here's a screenshot of what it looks like for me ( Atom v.1.49, MacOS 10.13.4):
> <img alt="delete" width="981" src="https://user-images.githubusercontent.com/61985120/88183010-31409000-cc31-11ea-9817-7b14514d6082.png">

+1 on this, after removing one of the "}'"s, I get a very similar display issue.

**Comment by lhoupert** [comment]
Hey guys same problems here, this fix didnt work.

**Comment by duongnosu** [comment]
I have the same problem using @yalin solution as well.
<img width="1409" alt="Screen Shot 2020-08-27 at 3 00 58 PM" src="https://user-images.githubusercontent.com/35271575/91499480-577fce00-e876-11ea-91cc-7c64fda96a76.png">

 Hope this will get fix soon

**Comment by padenalex** [comment]
bump

**Comment by madSec** [comment]
I have the same issue on Linux Mint 20 using Atom 1.51.0 and jupyter-notebook package version 0.0.10, first the error and after trying @yalin fix the issue with wrong displaying.

**Comment by yalin** [comment]
As I see everyone has the same problem :)
The project README file has a section at the top

> This project does not have any active maintainers. We recommend that you use [nteract](https://nteract.io/desktop), a native notebook application built using Electron, React (like this project), Redux, and RxJS, or [Hydrogen](https://nteract.io/atom), a LightTable-inspired package for Atom that allows users to run code blocks and selections using Jupyter kernels.

The bracket solution that I wrote above is for a temporary solution and also for an open-source fix. It's not an official solution. Owners of this project should fix the main issue but as I see, the project is deprecated. The best thing to do is; either you fix the issue of this open-source project on your own, or use the new applications which the owners recommend.

cheers! :rocket: 
and stay safe :mask:

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/105350282-7ca61c00-5c1d-11eb-85d2-6be04d2d1ae9.png)

**Comment by aminya** [comment]
> As I see everyone has the same problem :)
> The project README file has a section at the top
> 
> > This project does not have any active maintainers. We recommend that you use [nteract](https://nteract.io/desktop), a native notebook application built using Electron, React (like this project), Redux, and RxJS, or [Hydrogen](https://nteract.io/atom), a LightTable-inspired package for Atom that allows users to run code blocks and selections using Jupyter kernels.
> 
> The bracket solution that I wrote above is for a temporary solution and also for an open-source fix. It's not an official solution. Owners of this project should fix the main issue but as I see, the project is deprecated. The best thing to do is; either you fix the issue of this open-source project on your own, or use the new applications which the owners recommend.
> 
> cheers! 🚀
> and stay safe 😷

Hi. The owner of @atom-community here. I am interested in providing the functionality of opening ipynb files (which is I think the only missing feature) inside Hydrogen.

If @jupyter is interested, I can become a member of @jupyter and take care of the maintenance. They can also transfer it to @atom-community as another alternative.

cc: @gnestor

**Comment by rkansal47** [comment]
Hi, have there been any updates on this issue?

**Comment by gnestor** [comment]
I'm not maintaining this repo any more and I don't think anyone else is, either. The Jupyter integration with VS Code is a good option these days.
