### ISSUE TITLE
Error while installing Jupyter-Notebook on Atom

### ISSUE THREAD

**Issue by danielnrocha** [jupyter/atom-notebook#109]
Hi, I tried to install Jupyter-Notebook on Atom but it keeps return the below error. Does anyone have any clue how to solve it? Thank you very much! By the way, I'm using Mac (macOS Catalina).

```
Installing “jupyter-notebook@0.0.10” failed.Hide output…

> bufferutil@1.2.1 install /private/var/folders/zp/305t4r7d3s74vxz_rjdg4njm0000gn/T/apm-install-dir-2020817-83917-elj9se.tg3w/node_modules/jupyter-notebook/node_modules/bufferutil
> node-gyp rebuild


> utf-8-validate@1.2.2 install /private/var/folders/zp/305t4r7d3s74vxz_rjdg4njm0000gn/T/apm-install-dir-2020817-83917-elj9se.tg3w/node_modules/jupyter-notebook/node_modules/utf-8-validate
> node-gyp rebuild


> pathwatcher@8.1.0 install /private/var/folders/zp/305t4r7d3s74vxz_rjdg4njm0000gn/T/apm-install-dir-2020817-83917-elj9se.tg3w/node_modules/jupyter-notebook/node_modules/pathwatcher
> node-gyp rebuild


npm WARN deprecated jupyter-js-services@0.21.1: This package has moved to @jupyterlab/services
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/zp/305t4r7d3s74vxz_rjdg4njm0000gn/T/apm-install-dir-2020817-83917-elj9se.tg3w/node_modules/jupyter-notebook/node_modules/bufferutil
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/zp/305t4r7d3s74vxz_rjdg4njm0000gn/T/apm-install-dir-2020817-83917-elj9se.tg3w/node_modules/jupyter-notebook/node_modules/utf-8-validate
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/zp/305t4r7d3s74vxz_rjdg4njm0000gn/T/apm-install-dir-2020817-83917-elj9se.tg3w/node_modules/jupyter-notebook/node_modules/pathwatcher
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/zp/305t4r7d3s74vxz_rjdg4njm0000gn/T/apm-install-dir-2020817-83917-elj9se.tg3w/package.json'
npm WARN apm-install-dir-2020817-83917-elj9se.tg3w No description
npm WARN apm-install-dir-2020817-83917-elj9se.tg3w No repository field.
npm WARN apm-install-dir-2020817-83917-elj9se.tg3w No README data
npm WARN apm-install-dir-2020817-83917-elj9se.tg3w No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules/jupyter-notebook/node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules/jupyter-notebook/node_modules/utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pathwatcher@8.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher@8.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pedrocerbino/.atom/.apm/_logs/2020-09-17T04_33_26_655Z-debug.log
```

**Comment by Hgnis-Raknahs** [comment]
this error also comes in windows device

**Comment by parthKalbag** [comment]
For MacOS you need to download XCode and for Windows Visual Studio (2017 or later) because it contains the C++ compilers as I was also facing the same issue in my windows machine and it was resolved by this method and for Visual Studio download Desktop Applications C++, Mobile Development C++ , etc.

**Comment by Cheukting** [comment]
I have encountered the same problem, I do have code CLI installed but apparently, it's broken for xcode12. The workaround is to install it from https://developer.apple.com/download/more/?=command%20line%20tools
