### ISSUE TITLE
The jupyter-notebook package doesn't install

### ISSUE THREAD

**Issue by purple-mustache** [jupyter/atom-notebook#113]
the package doesn't install no matter how many times I try

**Comment by hopeJRD** [comment]
Please provide the log

**Comment by vpicouet** [comment]
on a mac:
```
apm install jupyter-notebook
Installing jupyter-notebook to /Users/Vincent/.atom/packages ✗

> bufferutil@1.2.1 install /private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/apm-install-dir-202237-8314-154p4xo.4izy/node_modules/jupyter-notebook/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> utf-8-validate@1.2.2 install /private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/apm-install-dir-202237-8314-154p4xo.4izy/node_modules/jupyter-notebook/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o

> pathwatcher@8.1.2 install /private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/apm-install-dir-202237-8314-154p4xo.4izy/node_modules/jupyter-notebook/node_modules/pathwatcher
> node-gyp rebuild

  CXX(target) Release/obj.target/pathwatcher/src/main.o

npm WARN deprecated jupyter-js-services@0.21.1: This package has moved to @jupyterlab/services
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated core-js@1.2.7: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
In file included from ../src/bufferutil.cc:7:
In file included from /Users/Vincent/.atom/.node-gyp/Library/Caches/node-gyp/9.4.4/include/node/v8.h:21:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/memory:667:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:417:
/Library/Developer/CommandLineTools/usr/include/c++/v1/cstddef:49:9: error: no member named 'ptrdiff_t' in the global namespace
using ::ptrdiff_t;
      ~~^
/Library/Developer/CommandLineTools/usr/include/c++/v1/cstddef:50:9: error: no member named 'size_t' in the global namespace
using ::size_t;
      ~~^
/Library/Developer/CommandLineTools/usr/include/c++/v1/cstddef:53:9: error: no member named 'max_align_t' in the global namespace
using ::max_align_t;
      ~~^
In file included from ../src/bufferutil.cc:7:
In file included from /Users/Vincent/.atom/.node-gyp/Library/Caches/node-gyp/9.4.4/include/node/v8.h:21:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/memory:667:
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1553:32: error: use of undeclared identifier 'size_t'; did you mean 'sizeof'?
    : public integral_constant<size_t, 0> {};
                               ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1553:38: error: expected expression
    : public integral_constant<size_t, 0> {};
                                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1555:32: error: use of undeclared identifier 'size_t'; did you mean 'sizeof'?
    : public integral_constant<size_t, rank<_Tp>::value + 1> {};
                               ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1555:38: error: expected expression
    : public integral_constant<size_t, rank<_Tp>::value + 1> {};
                                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1555:51: error: expected class name
    : public integral_constant<size_t, rank<_Tp>::value + 1> {};
                                                  ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1556:22: error: unknown type name 'size_t'
template <class _Tp, size_t _Np> struct _LIBCPP_TEMPLATE_VIS rank<_Tp[_Np]>
                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1557:32: error: use of undeclared identifier 'size_t'; did you mean 'sizeof'?
    : public integral_constant<size_t, rank<_Tp>::value + 1> {};
                               ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1557:38: error: expected expression
    : public integral_constant<size_t, rank<_Tp>::value + 1> {};
                                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1557:51: error: expected class name
    : public integral_constant<size_t, rank<_Tp>::value + 1> {};
                                                  ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1569:21: error: unknown type name 'size_t'
template<class _Tp, size_t _Dim = 0>
                    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1571:25: error: use of undeclared identifier 'size_t'; did you mean 'sizeof'?
    : integral_constant<size_t, __array_extent(_Tp, _Dim)> { };
                        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1571:31: error: expected expression
    : integral_constant<size_t, __array_extent(_Tp, _Dim)> { };
                              ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1605:22: error: unknown type name 'size_t'
template <class _Tp, size_t _Np> struct _LIBCPP_TEMPLATE_VIS remove_extent<_Tp[_Np]>
                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1618:22: error: unknown type name 'size_t'
template <class _Tp, size_t _Np> struct _LIBCPP_TEMPLATE_VIS remove_all_extents<_Tp[_Np]>
                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1944:32: error: use of undeclared identifier 'size_t'; did you mean 'sizeof'?
    : public integral_constant<size_t, _LIBCPP_ALIGNOF(_Tp)> {};
                               ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1944:38: error: expected expression
    : public integral_constant<size_t, _LIBCPP_ALIGNOF(_Tp)> {};
                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/AppTranslocation/1B1F107B-DD81-4444-AAF9-D97167F2EE40/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/AppTranslocation/1B1F107B-DD81-4444-AAF9-D97167F2EE40/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/AppTranslocation/1B1F107B-DD81-4444-AAF9-D97167F2EE40/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/apm-install-dir-202237-8314-154p4xo.4izy/node_modules/jupyter-notebook/node_modules/bufferutil
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
In file included from ../src/validation.cc:7:
In file included from /Users/Vincent/.atom/.node-gyp/Library/Caches/node-gyp/9.4.4/include/node/v8.h:21:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/memory:667:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:417:
/Library/Developer/CommandLineTools/usr/include/c++/v1/cstddef:49:9: error: no member named 'ptrdiff_t' in the global namespace
using ::ptrdiff_t;
      ~~^
/Library/Developer/CommandLineTools/usr/include/c++/v1/cstddef:50:9: error: no member named 'size_t' in the global namespace
using ::size_t;
      ~~^
/Library/Developer/CommandLineTools/usr/include/c++/v1/cstddef:53:9: error: no member named 'max_align_t' in the global namespace
using ::max_align_t;
      ~~^
In file included from ../src/validation.cc:7:
In file included from /Users/Vincent/.atom/.node-gyp/Library/Caches/node-gyp/9.4.4/include/node/v8.h:21:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/memory:667:
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1553:32: error: use of undeclared identifier 'size_t'; did you mean 'sizeof'?
    : public integral_constant<size_t, 0> {};
                               ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1553:38: error: expected expression
    : public integral_constant<size_t, 0> {};
                                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1555:32: error: use of undeclared identifier 'size_t'; did you mean 'sizeof'?
    : public integral_constant<size_t, rank<_Tp>::value + 1> {};
                               ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1555:38: error: expected expression
    : public integral_constant<size_t, rank<_Tp>::value + 1> {};
                                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1555:51: error: expected class name
    : public integral_constant<size_t, rank<_Tp>::value + 1> {};
                                                  ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1556:22: error: unknown type name 'size_t'
template <class _Tp, size_t _Np> struct _LIBCPP_TEMPLATE_VIS rank<_Tp[_Np]>
                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1557:32: error: use of undeclared identifier 'size_t'; did you mean 'sizeof'?
    : public integral_constant<size_t, rank<_Tp>::value + 1> {};
                               ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1557:38: error: expected expression
    : public integral_constant<size_t, rank<_Tp>::value + 1> {};
                                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1557:51: error: expected class name
    : public integral_constant<size_t, rank<_Tp>::value + 1> {};
                                                  ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1569:21: error: unknown type name 'size_t'
template<class _Tp, size_t _Dim = 0>
                    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1571:25: error: use of undeclared identifier 'size_t'; did you mean 'sizeof'?
    : integral_constant<size_t, __array_extent(_Tp, _Dim)> { };
                        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1571:31: error: expected expression
    : integral_constant<size_t, __array_extent(_Tp, _Dim)> { };
                              ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1605:22: error: unknown type name 'size_t'
template <class _Tp, size_t _Np> struct _LIBCPP_TEMPLATE_VIS remove_extent<_Tp[_Np]>
                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1618:22: error: unknown type name 'size_t'
template <class _Tp, size_t _Np> struct _LIBCPP_TEMPLATE_VIS remove_all_extents<_Tp[_Np]>
                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1944:32: error: use of undeclared identifier 'size_t'; did you mean 'sizeof'?
    : public integral_constant<size_t, _LIBCPP_ALIGNOF(_Tp)> {};
                               ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1944:38: error: expected expression
    : public integral_constant<size_t, _LIBCPP_ALIGNOF(_Tp)> {};
                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/AppTranslocation/1B1F107B-DD81-4444-AAF9-D97167F2EE40/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/AppTranslocation/1B1F107B-DD81-4444-AAF9-D97167F2EE40/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/AppTranslocation/1B1F107B-DD81-4444-AAF9-D97167F2EE40/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/apm-install-dir-202237-8314-154p4xo.4izy/node_modules/jupyter-notebook/node_modules/utf-8-validate
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
In file included from ../src/main.cc:1:
In file included from ../src/common.h:4:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/vector:275:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:95:
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:137:77: error: use of undeclared identifier 'wcschr'
wchar_t* __libcpp_wcschr(const wchar_t* __s, wchar_t __c) {return (wchar_t*)wcschr(__s, __c);}
                                                                            ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:144:87: error: use of undeclared identifier 'wcspbrk'
wchar_t* __libcpp_wcspbrk(const wchar_t* __s1, const wchar_t* __s2) {return (wchar_t*)wcspbrk(__s1, __s2);}
                                                                                      ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:151:78: error: use of undeclared identifier 'wcsrchr'; did you mean 'wcschr'?
wchar_t* __libcpp_wcsrchr(const wchar_t* __s, wchar_t __c) {return (wchar_t*)wcsrchr(__s, __c);}
                                                                             ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:139:16: note: 'wcschr' declared here
const wchar_t* wcschr(const wchar_t* __s, wchar_t __c) {return __libcpp_wcschr(__s, __c);}
               ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:158:86: error: use of undeclared identifier 'wcsstr'; did you mean 'wcschr'?
wchar_t* __libcpp_wcsstr(const wchar_t* __s1, const wchar_t* __s2) {return (wchar_t*)wcsstr(__s1, __s2);}
                                                                                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:141:16: note: 'wcschr' declared here
      wchar_t* wcschr(      wchar_t* __s, wchar_t __c) {return __libcpp_wcschr(__s, __c);}
               ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:158:86: error: no matching function for call to 'wcschr'
wchar_t* __libcpp_wcsstr(const wchar_t* __s1, const wchar_t* __s2) {return (wchar_t*)wcsstr(__s1, __s2);}
                                                                                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:141:16: note: candidate disabled: <no message provided>
      wchar_t* wcschr(      wchar_t* __s, wchar_t __c) {return __libcpp_wcschr(__s, __c);}
               ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:158:93: error: cannot initialize a parameter of type 'wchar_t *' with an lvalue of type 'const wchar_t *'
wchar_t* __libcpp_wcsstr(const wchar_t* __s1, const wchar_t* __s2) {return (wchar_t*)wcsstr(__s1, __s2);}
                                                                                            ^~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:141:38: note: passing argument to parameter '__s' here
      wchar_t* wcschr(      wchar_t* __s, wchar_t __c) {return __libcpp_wcschr(__s, __c);}
                                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:165:60: error: unknown type name 'size_t'
wchar_t* __libcpp_wmemchr(const wchar_t* __s, wchar_t __c, size_t __n) {return (wchar_t*)wmemchr(__s, __c, __n);}
                                                           ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:167:57: error: unknown type name 'size_t'
const wchar_t* wmemchr(const wchar_t* __s, wchar_t __c, size_t __n) {return __libcpp_wmemchr(__s, __c, __n);}
                                                        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:169:57: error: unknown type name 'size_t'
      wchar_t* wmemchr(      wchar_t* __s, wchar_t __c, size_t __n) {return __libcpp_wmemchr(__s, __c, __n);}
                                                        ^
In file included from ../src/main.cc:1:
In file included from ../src/common.h:4:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/vector:275:
/Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:189:14: error: use of undeclared identifier 'mbstate_t'
typedef fpos<mbstate_t>    streampos;
             ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:190:14: error: use of undeclared identifier 'mbstate_t'
typedef fpos<mbstate_t>    wstreampos;
             ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:195:14: error: use of undeclared identifier 'mbstate_t'
typedef fpos<mbstate_t>    u16streampos;
             ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:196:14: error: use of undeclared identifier 'mbstate_t'
typedef fpos<mbstate_t>    u32streampos;
             ^
In file included from ../src/main.cc:1:
In file included from ../src/common.h:4:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/vector:276:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__bit_reference:14:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/bit:58:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/limits:105:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:417:
/Library/Developer/CommandLineTools/usr/include/c++/v1/cstddef:49:9: error: no member named 'ptrdiff_t' in the global namespace
using ::ptrdiff_t;
      ~~^
/Library/Developer/CommandLineTools/usr/include/c++/v1/cstddef:50:9: error: no member named 'size_t' in the global namespace
using ::size_t;
      ~~^
/Library/Developer/CommandLineTools/usr/include/c++/v1/cstddef:53:9: error: no member named 'max_align_t' in the global namespace
using ::max_align_t;
      ~~^
In file included from ../src/main.cc:1:
In file included from ../src/common.h:4:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/vector:276:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__bit_reference:14:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/bit:58:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/limits:105:
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1553:32: error: use of undeclared identifier 'size_t'; did you mean 'sizeof'?
    : public integral_constant<size_t, 0> {};
                               ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1553:38: error: expected expression
    : public integral_constant<size_t, 0> {};
                                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:1555:32: error: use of undeclared identifier 'size_t'; did you mean 'sizeof'?
    : public integral_constant<size_t, rank<_Tp>::value + 1> {};
                               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/pathwatcher/src/main.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/AppTranslocation/1B1F107B-DD81-4444-AAF9-D97167F2EE40/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/AppTranslocation/1B1F107B-DD81-4444-AAF9-D97167F2EE40/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/AppTranslocation/1B1F107B-DD81-4444-AAF9-D97167F2EE40/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/apm-install-dir-202237-8314-154p4xo.4izy/node_modules/jupyter-notebook/node_modules/pathwatcher
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/m8/f6l41h_51qxdzrz8p1xqr3f80000gp/T/apm-install-dir-202237-8314-154p4xo.4izy/package.json'
npm WARN apm-install-dir-202237-8314-154p4xo.4izy No description
npm WARN apm-install-dir-202237-8314-154p4xo.4izy No repository field.
npm WARN apm-install-dir-202237-8314-154p4xo.4izy No README data
npm WARN apm-install-dir-202237-8314-154p4xo.4izy No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules/jupyter-notebook/node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules/jupyter-notebook/node_modules/utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pathwatcher@8.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pathwatcher@8.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Vincent/.atom/.apm/_logs/2022-04-07T15_08_49_569Z-debug.log
```
