### ISSUE TITLE
Uncaught TypeError: _transformimeJupyterTransformers.StreamTransformer is not a function

### ISSUE THREAD

**Issue by auneri** [jupyter/atom-notebook#12]
[Enter steps to reproduce below:]

1. Simply opening a .ipynb file.

**Atom Version**: 1.2.4
**System**: Windows 7
**Thrown From**: [jupyter-notebook](https://github.com/jupyter/atom-notebook) package, v0.0.3

### Stack Trace

Uncaught TypeError: _transformimeJupyterTransformers.StreamTransformer is not a function

```
At /C:/Users/auneri1/.atom/packages/jupyter-notebook/lib/notebook-editor.js:275

TypeError: _transformimeJupyterTransformers.StreamTransformer is not a function
    at new NotebookEditor (C:/Users/auneri1/.atom/packages/jupyter-notebook/lib/notebook-editor.js:45:42)
    at openURI (C:/Users/auneri1/.atom/packages/jupyter-notebook/lib/main.js:71:80)
    at Workspace.module.exports.Workspace.openURIInPane (C:\Users\auneri1\AppData\Local\atom\app-1.2.4\resources\app.asar\src\workspace.js:454:22)
    at Workspace.module.exports.Workspace.open (C:\Users\auneri1\AppData\Local\atom\app-1.2.4\resources\app.asar\src\workspace.js:393:19)
    at ProjectView.module.exports.FuzzyFinderView.openPath (C:\Users\auneri1\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\fuzzy-finder\lib\fuzzy-finder-view.js:208:31)
    at ProjectView.module.exports.FuzzyFinderView.confirmed (C:\Users\auneri1\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\fuzzy-finder\lib\fuzzy-finder-view.js:328:21)
    at ProjectView.module.exports.FuzzyFinderView.confirmSelection (C:\Users\auneri1\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\fuzzy-finder\lib\fuzzy-finder-view.js:296:19)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\auneri1\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\auneri1\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\auneri1\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\auneri1\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\auneri1\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\auneri1\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (C:\Users\auneri1\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:06.9.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:03.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-todo",
      "markdown-preview",
      "metrics",
      "open-on-github",
      "package-generator",
      "styleguide",
      "language-gfm",
      "vim-mode"
    ],
    "audioBeep": false,
    "autoHideMenuBar": true,
    "openEmptyEditorOnStart": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".ipynb_checkpoints"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-cli-diff, v1.1.0
autocomplete-cmake, v0.3.1
autocomplete-python, v0.10.7
browser-plus, v0.0.54
build, v0.49.2
color-picker, v2.0.14
file-icons, v1.6.13
jupyter-notebook, v0.0.3
language-batch, v0.3.3
language-cmake, v0.1.4
language-fish-shell, v1.0.2
language-latex, v0.6.1
language-matlab, v0.1.1
language-pfm, v0.82.0
language-reg, v0.0.0
line-diff-details, v1.1.3
linter, v1.11.3
linter-chktex, v1.2.3
linter-cpplint, v1.0.0
linter-csslint, v1.1.0
linter-flake8, v1.9.2
linter-htmlhint, v0.2.1
linter-jshint, v1.2.1
markdown-preview-plus, v2.2.2
mathjax-wrapper, v0.1.0
minimap, v4.16.2
pigments, v0.19.1
preview-inline, v0.5.1
project-manager, v2.6.5
set-syntax, v0.3.0
Sublime-Style-Column-Selection, v1.3.0
symbols-tree-view, v0.10.1
sync-settings, v0.6.0
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by monkpit** [comment]
Just got the same thing with a similar setup - Windows 7, Atom 1.2.4.

**Comment by hsz1273327** [comment]
same issue in Mac osx10.11.1 atom 1.2.4

**Comment by theideasmith** [comment]
I also got this issue Mac OS X 10.11.1 Atom 1.2.4. Same as @hsz1273327

**Comment by alexandercbooth** [comment]
I have the same issue as @hsz1273327, except I am running atom 1.4.0-dev-3da93a1. This is an excellent and important addition to atom, so thanks in advance!

**Comment by gnestor** [comment]
transformime-jupyter-transformers 0.2.0 does not expose StreamTransformer anymore so I'm downgrading back to 0.0.4.

https://github.com/jupyter/atom-notebook/commit/e23e99f07f15878a2af613d82846229feabdf0a2 fixes this.

**Comment by theideasmith** [comment]
I cloned the git repository and also tried installing with `apm` and this error persists:

```
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [jupyter-notebook](https://github.com/jupyter/atom-notebook) package, v0.0.3


### Stack Trace

Uncaught TypeError: _transformimeJupyterTransformers.StreamTransformer is not a function

```
At /Users/akivalipshitz/.atom/packages/jupyter-notebook/lib/notebook-editor.js:45

TypeError: _transformimeJupyterTransformers.StreamTransformer is not a function
    at new NotebookEditor (/Users/akivalipshitz/.atom/packages/jupyter-notebook/lib/notebook-editor.js:45:42)
    at openURI (/Users/akivalipshitz/.atom/packages/jupyter-notebook/lib/main.js:71:80)
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:454:22)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:393:19)
    at TreeView.module.exports.TreeView.openSelectedEntry (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:736:31)
    at TreeView.module.exports.TreeView.entryClicked (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:462:18)
    at tree-view-file.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:183:26)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  4x -2:05.9.0 core:copy (div.package-readme.native-key-bindings)
     -0:02.2.0 core:close (div.package-readme.native-key-bindings)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai-galaxy-syntax-for-one-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Parinfer, v0.9.0
color-picker, v2.0.14
haskell-grammar, v0.4.0
jupyter-notebook, v0.0.3
language-haskell, v1.4.12
language-ipynb, v1.3.0
minimap, v4.15.2
minimap-git-diff, v4.1.8
monokai-galaxy-syntax-for-one-dark, v0.7.0

# Dev
No dev packages
```

**Comment by gnestor** [comment]
I just pushed 0.0.4. Update and test again.
