### ISSUE TITLE
Failing to start jupyter

### ISSUE THREAD

**Issue by radaniba** [jupyter/atom-notebook#33]
Hello 

I think this was reported before, if yes feel free to link this issue to another one but I am reporting the error message I think no one reported yet :`

```
notebook-editor.js:33 NotebookEditor created for /Users/Rad/Documents/Dev/quotawatcher/QuotaWatcher.ipynb
notebook-editor.js:258 kernelGateway.stderr Traceback (most recent call last):
  File "/usr/local/bin/jupyter", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/jupyter_core/command.py", line 151, in main
    _execvp(command, sys.argv[1:])
  File "/Library/Python/2.7/site-packages/jupyter_core/command.py", line 104, in _execvp
    os.execvp(cmd, argv)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 346, in execvp
    _execvpe(file, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 382, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 20] Not a directory
```

```
apm  1.5.0
npm  2.13.3
node 0.10.40
python 2.7.10

git 2.5.0
```

Jupyter is added to the settings and atom started with command line

Jupyter added to PATH too, but still no success in getting this package working

Help is appreciated

**Comment by gnestor** [comment]
Have you confirmed that the path of your jupyter (and Jupyter Kernel Gateway) is `/usr/local/bin/jupyter`?

**Comment by radaniba** [comment]
I had to install Kernel Gateway (and it didnt work) but strangely i did a `pip install --update` for the gateway and it worked. Thanks

**Comment by gnestor** [comment]
:ok_hand:
