### ISSUE TITLE
all Python cells throw AttributError:  'list' object has no attribute 'isspace'

### ISSUE THREAD

**Issue by kfix** [jupyter/atom-notebook#38]
OSX 10.11.3
Atom 1.5.3
Python 3.5.1
apm: jupyter-notebook: 0.0.9
pip: notebook: 4.1.0

Every time I try to execute a cell, this is the result:
```
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 175, in do_execute
    shell.run_cell(code, store_history=store_history, silent=silent)

  File "/usr/local/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2629, in run_cell
    if (not raw_cell) or raw_cell.isspace():

AttributeError: 'list' object has no attribute 'isspace'
```

**Comment by gnestor** [comment]
@rgbkrk Any ideas?

**Comment by rgbkrk** [comment]
No clue there. Version drift between the kernel gateway and the ipython kernel?

Have you tried out any of the JS packages we've been making @gnestor?

**Comment by gnestor** [comment]
@rgbkrk Not yet but I think it's time to start!

**Comment by kfix** [comment]
Upgraded jupyter_kernel_gateway from 0.3.1 to 0.4.0. No change.
Maybe the plugin needs to do a little enforcement and print an idiot warning?

**Comment by leonqli** [comment]
Same here. Anybody has a resolution?

**Comment by wandonye** [comment]
Same here

**Comment by rornor** [comment]
here too

**Comment by boomft** [comment]
Same here. @gnestor @rgbkrk

**Comment by iikulikov** [comment]
The same here. @gnestor @rgbkrk

**Comment by rgbkrk** [comment]
Once we have the prebuilt zmq story better underway, I'll be happy to come back to this repo to make it a fully standalone (no need for kernel gateway) Atom package, like [Hydrogen](https://github.com/nteract/hydrogen). Right now I don't have time to assist with this package, though I'll happily merge PRs that help push us towards the right efforts. Most of my open source node+jupyter time is in the [nteract org](https://github.com/nteract).

**Comment by shierve** [comment]
Any solutions?

**Comment by wiheto** [comment]
Another one here. 
Ubuntu: 16.04
Atom: 1.7.2
Python: 3.5.1
jupyter-notebook: 0.0.9

**Comment by wiheto** [comment]
Installed latest Atom version (1.10.2), now I have problems opening jypyter server: https://github.com/jupyter/atom-notebook/issues/55

**Comment by adammunich** [comment]
This happens on line 2190 of interactive_shell.py for me

```
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py in run_cell_async(self, raw_cell, store_history, silent, shell_futures)
   2908         result = ExecutionResult(info)
   2909 
-> 2910         if (not raw_cell) or raw_cell.isspace():
   2911             self.last_execution_succeeded = True
   2912             self.last_execution_result = result

AttributeError: 'builtin_function_or_method' object has no attribute 'isspace'
Out[5]: 'None'

In [6]: str(interactive_variables['interactive_console'].run_cell(print, True).result)    
```

Seems like it could be solved with a simple try/except
