### ISSUE TITLE
Uncaught Error: Kernel is not ready to send a message

### ISSUE THREAD

**Issue by cnHeider** [jupyter/atom-notebook#39]
Enter steps to reproduce below:  1. ... 2. ... **Atom Version**: 1.6.0-beta6-532c45b **System**: Debian GNU/Linux **Thrown From**:  jupyter-notebook  https://github.com/jupyter/atom-notebook  package, v0.0.9 ### Stack Trace Uncaught Error: Kernel is not ready to send a message     At /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactErrorUtils.js:53 Error: Kernel is not ready to send a message at Error  native  at Kernel.execute  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/jupyter-js-services/lib/kernel.js:622:19  at NotebookEditor.runCell  /home/heider/.atom/packages/jupyter-notebook/lib/notebook-editor.js:186:29  at Object.NotebookEditor.onAction  as ID_1   /home/heider/.atom/packages/jupyter-notebook/lib/notebook-editor.js:108:16  at Dispatcher._invokeCallback  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/flux/lib/Dispatcher.js:198:24  at Dispatcher.dispatch  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/flux/lib/Dispatcher.js:174:14  at runActiveCell  /home/heider/.atom/packages/jupyter-notebook/lib/notebook-editor-view.js:74:16  at Object.invokeGuardedCallback  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactErrorUtils.js:27:12  at executeDispatch  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/EventPluginUtils.js:79:21  at Object.executeDispatchesInOrder  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/EventPluginUtils.js:102:5  at executeDispatchesAndRelease  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/EventPluginHub.js:43:22  at executeDispatchesAndReleaseTopLevel  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/EventPluginHub.js:54:10  at Array.forEach  native  at forEachAccumulated  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/forEachAccumulated.js:23:9  at Object.EventPluginHub.processEventQueue  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/EventPluginHub.js:259:7  at runEventQueueInBatch  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactEventEmitterMixin.js:18:18  at Object.ReactEventEmitterMixin.handleTopLevel  as _handleTopLevel   /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactEventEmitterMixin.js:34:5  at handleTopLevelWithoutPath  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactEventListener.js:93:24  at handleTopLevelImpl  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactEventListener.js:73:3  at ReactDefaultBatchingStrategyTransaction.Mixin.perform  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/Transaction.js:136:20  at Object.ReactDefaultBatchingStrategy.batchedUpdates  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19  at Object.batchedUpdates  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactUpdates.js:94:20  at ReactEventListener.dispatchEvent  /home/heider/github/dotfiles/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactEventListener.js:204:20      ### Commands     -1:03.3.0 snippets:next-tab-stop  atom-text-editor.editor.is-focused  -1:03.3.0 snippets:expand  atom-text-editor.editor.is-focused  -1:03.1.0 editor:indent  atom-text-editor.editor.is-focused  8x -1:02.5.0 core:backspace  atom-text-editor.editor.is-focused  -0:54.7.0 markdown-WRITEr:insert-new-line  atom-text-editor.editor.is-focused  -0:54.7.0 editor:newline  atom-text-editor.editor.is-focused  -0:53.9.0 core:backspace  atom-text-editor.editor.is-focused  -0:53.6.0 jupyter-notebook-atom:run  atom-text-editor.editor.is-focused  -0:52.1.0 markdown-WRITEr:insert-new-line  atom-text-editor.editor.is-focused  -0:52.1.0 editor:newline  atom-text-editor.editor.is-focused  2x -0:51.4.0 core:backspace  atom-text-editor.editor.is-focused  2x -0:49.2.0 jupyter-notebook-atom:run  atom-text-editor.editor.is-focused  -0:11.6.0 advanced-OPEN-file:toggle  atom-text-editor.editor.is-focused  40x -0:10.5.0 core:backspace  atom-text-editor.path-input.editor.mini.is-focused  2x -0:05.9.0 advanced-OPEN-file:move-cursor-down  atom-text-editor.path-input.editor.mini.is-focused  -0:05.4.0 core:CONFIRM  atom-text-editor.path-input.editor.mini.is-focused      ### Config    json { core : { audioBeep : false, autoHideMenuBar : true, themes :   solarized-one-light-ui , solarized-light-syntax   } }     ### Installed Packages    coffee # User advanced-OPEN-file, v0.14.3 autocomplete-clang, v0.8.9 autocomplete-go, v0.2.0 autocomplete-python, v1.7.0 build, v0.55.0 color-picker, v2.1.1 cursor-blink-interval, v0.3.1 environment, v1.1.1 git-log, v0.4.1 go-config, v0.3.3 go-get, v0.1.1 jupyter-notebook, v0.0.9 language-gitignore, v0.2.0 language-ini, v1.14.0 language-latex, v0.6.1 latexer, v0.3.0 linter, v1.11.3 linter-chktex, v1.2.5 linter-gcc, v0.6.8 linter-markdown, v1.5.0 markdown-preview-OPENer, v0.1.1 markdown-scroll-sync, v2.1.2 markdown-WRITEr, v2.3.2 minimap, v4.20.0 minimap-bookmarks, v0.3.0 minimap-codeglance, v0.4.5 minimap-cursorline, v0.1.0 minimap-find-and-replace, v4.5.0 minimap-git-diff, v4.2.0 minimap-highlight-selected, v4.4.0 minimap-linter, v1.1.1 minimap-pigments, v0.2.0 minimap-selection, v4.4.0 package-sync, v1.0.0 pigments, v0.24.4 platformio-ide, v1.0.5 platformio-ide-terminal, v2.0.2 project-manager, v2.7.6 python-tools, v0.6.7 solarized-one-light-ui, v1.1.11 tool-bar, v0.3.0 travis-ci-status, v1.0.0 you-complete-me, v0.7.1 # Dev No dev packages

**Comment by gnestor** [comment]
@cnHeider It sounds like jupyter is not in Atom's PATH, therefore the `jupyter kernelgateway`command used by atom-notebook is not spawning a kernel gateway instance. 

1. Run `which jupyter` or `jupyter --paths` to determine where your jupyter binary is located
2. In Atom, run `process.env.PATH` and confirm that the path to your jupyter binary is included in Atom's PATH
3. If it's not included, add it to atom-notebook's settings (Command Pallette > Settings View > View Installed Packages > jupyter-notebook > Path to jupyter binary

If it is included, confirm that jupyter and jupyter kernel gateway is installed: `pip3 install jupyter jupyter_kernel_gateway`
