### ISSUE TITLE
Uncaught TypeError: Cannot set property 'focus' of undefined

### ISSUE THREAD

**Issue by cdsousa** [jupyter/atom-notebook#4]
Steps to reproduce:

1. Open Atom
2. Open some .ipynb file

**Atom Version**: 1.0.5
**System**: Ubuntu 15.04
**Thrown From**: [jupyter-notebook](https://github.com/willwhitney/jupyter-notebook-atom) package, v0.0.1

### Stack Trace

Uncaught TypeError: Cannot set property 'focus' of undefined

```
At /home/CSousa_Personal/Desktop/atom-packages/atom-notebook/lib/notebook-editor.js:295

TypeError: Cannot set property 'focus' of undefined
  at NotebookEditor.loadNotebookFile (/home/CSousa_Personal/Desktop/atom-packages/atom-notebook/lib/notebook-editor.js:295:39)
  at new NotebookEditor (/home/CSousa_Personal/Desktop/atom-packages/atom-notebook/lib/notebook-editor.js:227:14)
  at openURI (/home/CSousa_Personal/Desktop/atom-packages/atom-notebook/lib/main.js:51:16)
  at Workspace.module.exports.Workspace.openURIInPane (/opt/atom/resources/app.asar/src/workspace.js:446:22)
  at Workspace.module.exports.Workspace.open (/opt/atom/resources/app.asar/src/workspace.js:379:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/opt/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:709:31)
  at TreeView.module.exports.TreeView.entryClicked (/opt/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:427:18)
  at tree-view-file.<anonymous> (/opt/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:178:26)
  at space-pen-div.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-div.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "vim-mode-visual-block",
      "seti-icons",
      "wrap-guide",
      "linter-julia",
      "link"
    ],
    "autoHideMenuBar": true,
    "followSymlinks": false
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.5.17
autocomplete-clang, v0.8.7
hidpi, v0.7.0
indent-detective, v0.1.0
ink, v0.0.0
jupyter-notebook, v0.0.1
keyboard-localization, v1.4.7
language-cmake, v0.1.4
language-cuda, v0.0.0
language-ini, v1.11.0
language-julia, v0.4.1
latex-completions, v0.3.0
linter, v1.3.4
linter-pep8, v1.0.1
minimap, v4.12.3
minimap-codeglance, v0.4.0
minimap-selection, v4.3.0
simple-drag-drop-text, v0.2.3

# Dev
No dev packages
```

**Comment by branning** [comment]
Same problem here, Atom 1.0.7, Windows 7

**Comment by gnestor** [comment]
This should be resolved now. Reopen if you are still running into this issue.
