### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by JLCCI** [jupyter/atom-notebook#41]
Thanks for your work with the package.

I tried to install and use jupyter-notebook inside atom but can't get through all the issues.

Arch Linux
atom 1.6.2
apm  1.6.0
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.7.4
jupyter 4.1.0

First of all I can't seem to install the package even thought everything else is installed (including pip packages). The error I get:

> utf-8-validate@1.2.1 install /tmp/apm-install-dir-11636-29851-1879d99/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-11636-29851-1879d99/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/tmp/apm-install-dir-11636-29851-1879d99/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate/build'

npm WARN peerDependencies The peer dependency phosphor-disposable@^1.0.5 included from jupyter-js-services will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency phosphor-signaling@^1.2.0 included from jupyter-js-services will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
In file included from ../../nan/nan_callbacks.h:83:0,
                 from ../../nan/nan.h:150,
                 from ../src/main.cc:1:
../../nan/nan_callbacks_12_inl.h:251:0: error: unterminated #if
 #if NODE_MODULE_VERSION > NODE_0_12_MODULE_VERSION
 ^
../../nan/nan_callbacks_12_inl.h:9:0: error: unterminated #ifndef
 #ifndef NAN_CALLBACKS_12_INL_H_
 ^
In file included from ../src/main.cc:1:0:
../../nan/nan.h:194:57: fatal error: nan_maybe_43_inl.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.5-1-ARCH
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11636-29851-1879d99/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.4.5-1-ARCH
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/user/.atom/.apm/.apmrc" "--userconfig" "/home/user/.atom/.apmrc" "install" "/tmp/d-11636-29851-kgdk5o/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

Somehow, after couple of tries, the package did install but it does not open the proper notebook screen and there is an error saying that some files are missing from the package.

Any ideas on how to fix it? Also, does linting and all the other packages properly work after opening the ipynb files?

Many thanks!

**Comment by JLCCI** [comment]
Any chance for some help? I did manage to install it (sometime it installs sometime it does not), but when I actually open an ipynb file Atom throws an error saying it is missing files from its folder. 

My friend tried to install the package and gets the same error (also on linux).

**Comment by cnHeider** [comment]
+1
`> runas@3.1.1 install /tmp/apm-install-dir-116319-7349-14f6afi/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-116319-7349-14f6afi/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
runas.target.mk:90: recipe for target 'Release/obj.target/runas/src/main.o' failed
make: Leaving directory '/tmp/apm-install-dir-116319-7349-14f6afi/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas/build'

> bufferutil@1.2.1 install /tmp/apm-install-dir-116319-7349-14f6afi/node_modules/jupyter-notebook/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-116319-7349-14f6afi/node_modules/jupyter-notebook/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/tmp/apm-install-dir-116319-7349-14f6afi/node_modules/jupyter-notebook/node_modules/ws/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /tmp/apm-install-dir-116319-7349-14f6afi/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-116319-7349-14f6afi/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/tmp/apm-install-dir-116319-7349-14f6afi/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate/build'

npm WARN peerDependencies The peer dependency phosphor-disposable@^1.0.5 included from jupyter-js-services will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency phosphor-signaling@^1.2.0 included from jupyter-js-services will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
In file included from ../../nan/nan_callbacks.h:83:0,
                 from ../../nan/nan.h:150,
                 from ../src/main.cc:1:
../../nan/nan_callbacks_12_inl.h:251:0: error: unterminated #if
 #if NODE_MODULE_VERSION > NODE_0_12_MODULE_VERSION
 ^
../../nan/nan_callbacks_12_inl.h:9:0: error: unterminated #ifndef
 #ifndef NAN_CALLBACKS_12_INL_H_
 ^
In file included from ../src/main.cc:1:0:
../../nan/nan.h:194:57: fatal error: nan_maybe_43_inl.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.0-1-amd64
gyp ERR! command "node" "/usr/local/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-116319-7349-14f6afi/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.4.0-1-amd64
npm ERR! argv "/usr/local/share/atom/resources/app/apm/bin/node" "/usr/local/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/heider/github/dotconfig/.atom/.apm/.apmrc" "--userconfig" "/home/heider/github/dotconfig/.atom/.apmrc" "install" "/tmp/d-116319-7349-1phi6d1/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116319-7349-14f6afi/npm-debug.log`

**Comment by JuanCabre** [comment]
I am also in Arch Linux and I am getting exactly the same error.

```
> runas@3.1.1 install /tmp/apm-install-dir-116321-28545-1q7vr0/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-116321-28545-1q7vr0/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
runas.target.mk:90: recipe for target 'Release/obj.target/runas/src/main.o' failed
make: Leaving directory '/tmp/apm-install-dir-116321-28545-1q7vr0/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas/build'

> bufferutil@1.2.1 install /tmp/apm-install-dir-116321-28545-1q7vr0/node_modules/jupyter-notebook/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-116321-28545-1q7vr0/node_modules/jupyter-notebook/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/tmp/apm-install-dir-116321-28545-1q7vr0/node_modules/jupyter-notebook/node_modules/ws/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /tmp/apm-install-dir-116321-28545-1q7vr0/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-116321-28545-1q7vr0/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/tmp/apm-install-dir-116321-28545-1q7vr0/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate/build'

npm WARN peerDependencies The peer dependency phosphor-disposable@^1.0.5 included from jupyter-js-services will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency phosphor-signaling@^1.2.0 included from jupyter-js-services will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
In file included from ../src/main.cc:1:0:
../../nan/nan.h:93:26: warning: backslash-newline at end of file
 #if defined(__GNUC__) && \
                          ^
../../nan/nan.h:94:6: error: missing ')' in expression
     !(defined(V8_DISABLE_DEPRECATIONS) && V8_DISABLE_DEPRECATIONS)
      ^
../../nan/nan.h:93:0: error: unterminated #if
 #if defined(__GNUC__) && \
 ^
In file included from ../src/main.cc:1:0:
../../nan/nan.h:20:0: error: unterminated #ifndef
 #ifndef NAN_H_
 ^
../src/main.cc: In function ‘bool Nan::{anonymous}::GetProperty(v8::Local<v8::Object>, const char*, v8::Local<v8::Value>*)’:
../src/main.cc:10:10: error: ‘Get’ is not a member of ‘Nan’
   return Nan::Get(obj, Nan::New<String>(key).ToLocalChecked()).ToLocal(value);
          ^
../src/main.cc:10:24: error: ‘New’ is not a member of ‘Nan’
   return Nan::Get(obj, Nan::New<String>(key).ToLocalChecked()).ToLocal(value);
                        ^
../src/main.cc:10:24: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:10:39: error: expected primary-expression before ‘>’ token
   return Nan::Get(obj, Nan::New<String>(key).ToLocalChecked()).ToLocal(value);
                                       ^
../src/main.cc:10:46: error: request for member ‘ToLocalChecked’ in ‘key’, which is of non-class type ‘const char*’
   return Nan::Get(obj, Nan::New<String>(key).ToLocalChecked()).ToLocal(value);
                                              ^
../src/main.cc: In function ‘void Nan::{anonymous}::Runas(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/main.cc:15:5: error: ‘ThrowTypeError’ is not a member of ‘Nan’
     Nan::ThrowTypeError("Bad argument");
     ^
../src/main.cc:54:28: error: ‘New’ is not a member of ‘Nan’
     Local<Object> result = Nan::New<Object>();
                            ^
../src/main.cc:54:28: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:54:43: error: expected primary-expression before ‘>’ token
     Local<Object> result = Nan::New<Object>();
                                           ^
../src/main.cc:54:45: error: expected primary-expression before ‘)’ token
     Local<Object> result = Nan::New<Object>();
                                             ^
../src/main.cc:56:14: error: ‘New’ is not a member of ‘Nan’
              Nan::New<String>("exitCode").ToLocalChecked(),
              ^
../src/main.cc:56:14: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:57:14: error: ‘New’ is not a member of ‘Nan’
              Nan::New<Integer>(code));
              ^
../src/main.cc:57:14: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:55:13: error: expected primary-expression before ‘(’ token
     Nan::Set(result,
             ^
../src/main.cc:56:14: error: ‘New’ is not a member of ‘Nan’
              Nan::New<String>("exitCode").ToLocalChecked(),
              ^
../src/main.cc:56:14: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:56:29: error: expected primary-expression before ‘>’ token
              Nan::New<String>("exitCode").ToLocalChecked(),
                             ^
../src/main.cc:56:43: error: request for member ‘ToLocalChecked’ in ‘("exitCode")’, which is of non-class type ‘const char [9]’
              Nan::New<String>("exitCode").ToLocalChecked(),
                                           ^
../src/main.cc:57:14: error: ‘New’ is not a member of ‘Nan’
              Nan::New<Integer>(code));
              ^
../src/main.cc:57:14: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:57:30: error: expected primary-expression before ‘>’ token
              Nan::New<Integer>(code));
                              ^
../src/main.cc:59:14: error: ‘New’ is not a member of ‘Nan’
              Nan::New<String>("stdout").ToLocalChecked(),
              ^
../src/main.cc:59:14: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:60:14: error: ‘New’ is not a member of ‘Nan’
              Nan::New<String>(std_output).ToLocalChecked());
              ^
../src/main.cc:60:14: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:58:13: error: expected primary-expression before ‘(’ token
     Nan::Set(result,
             ^
../src/main.cc:59:14: error: ‘New’ is not a member of ‘Nan’
              Nan::New<String>("stdout").ToLocalChecked(),
              ^
../src/main.cc:59:14: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:59:29: error: expected primary-expression before ‘>’ token
              Nan::New<String>("stdout").ToLocalChecked(),
                             ^
../src/main.cc:59:41: error: request for member ‘ToLocalChecked’ in ‘("stdout")’, which is of non-class type ‘const char [7]’
              Nan::New<String>("stdout").ToLocalChecked(),
                                         ^
../src/main.cc:60:14: error: ‘New’ is not a member of ‘Nan’
              Nan::New<String>(std_output).ToLocalChecked());
              ^
../src/main.cc:60:14: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:60:29: error: expected primary-expression before ‘>’ token
              Nan::New<String>(std_output).ToLocalChecked());
                             ^
../src/main.cc:60:43: error: ‘std::__cxx11::string {aka class std::__cxx11::basic_string<char>}’ has no member named ‘ToLocalChecked’
              Nan::New<String>(std_output).ToLocalChecked());
                                           ^
../src/main.cc:62:14: error: ‘New’ is not a member of ‘Nan’
              Nan::New<String>("stderr").ToLocalChecked(),
              ^
../src/main.cc:62:14: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:63:14: error: ‘New’ is not a member of ‘Nan’
              Nan::New<String>(std_error).ToLocalChecked());
              ^
../src/main.cc:63:14: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:61:13: error: expected primary-expression before ‘(’ token
     Nan::Set(result,
             ^
../src/main.cc:62:14: error: ‘New’ is not a member of ‘Nan’
              Nan::New<String>("stderr").ToLocalChecked(),
              ^
../src/main.cc:62:14: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:62:29: error: expected primary-expression before ‘>’ token
              Nan::New<String>("stderr").ToLocalChecked(),
                             ^
../src/main.cc:62:41: error: request for member ‘ToLocalChecked’ in ‘("stderr")’, which is of non-class type ‘const char [7]’
              Nan::New<String>("stderr").ToLocalChecked(),
                                         ^
../src/main.cc:63:14: error: ‘New’ is not a member of ‘Nan’
              Nan::New<String>(std_error).ToLocalChecked());
              ^
../src/main.cc:63:14: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:63:29: error: expected primary-expression before ‘>’ token
              Nan::New<String>(std_error).ToLocalChecked());
                             ^
../src/main.cc:63:42: error: ‘std::__cxx11::string {aka class std::__cxx11::basic_string<char>}’ has no member named ‘ToLocalChecked’
              Nan::New<String>(std_error).ToLocalChecked());
                                          ^
../src/main.cc:66:31: error: ‘New’ is not a member of ‘Nan’
     info.GetReturnValue().Set(Nan::New<Integer>(code));
                               ^
../src/main.cc:66:31: note: suggested alternative:
In file included from ../../nan/nan.h:46:0,
                 from ../src/main.cc:1:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node_buffer.h:53:40: note:   ‘node::Buffer::New’
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
../src/main.cc:66:47: error: expected primary-expression before ‘>’ token
     info.GetReturnValue().Set(Nan::New<Integer>(code));
                                               ^
../src/main.cc: In function ‘void Nan::{anonymous}::Init(v8::Handle<v8::Object>)’:
../src/main.cc:71:3: error: ‘SetMethod’ is not a member of ‘Nan’
   Nan::SetMethod(exports, "runas", Runas);
   ^
In file included from ../../nan/nan.h:45:0,
                 from ../src/main.cc:1:
../src/main.cc: At global scope:
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node.h:432:3: error: expected ‘}’ at end of input
   }
   ^
/home/juarch/.atom/.node-gyp/.node-gyp/0.36.12/src/node.h:454:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)
   ^
../src/main.cc:76:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(runas, Init)
 ^
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.5.1-1-ARCH
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-116321-28545-1q7vr0/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.5.1-1-ARCH
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/juarch/.atom/.apm/.apmrc" "--userconfig" "/home/juarch/.atom/.apmrc" "install" "/tmp/d-116321-28545-1yw3fbf/package.tgz" "--target=0.36.12" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116321-28545-1q7vr0/npm-debug.log
```

**Comment by kingjr** [comment]
In my case, this error seemed to have been to anaconda.  To quote @n-riesco: "`npm` uses `node-gyp`, and `node-gyp` uses `gyp`. Unfortunately, Anaconda overwrites `gyp` with a different version" (https://github.com/n-riesco/ijavascript/issues/35).

The work around is to temporarily move anaconda for the install: e.g. in linux: (change `username` by your own username)

```
$ mv /home/username/anaconda /home/coldmoon/anaconda.bak
$ apm install jupyter-notebook
$ mv /home/username/anaconda.bak /home/coldmoon/anaconda
```

**Comment by JLCCI** [comment]
The errors is still there even thought I have a regular Python version and everything installed through pip. Although it seems that this module is no longer maintained or the creator does not have time to maintain it. 

Guess we should look for alternatives to run python notebook.

**Comment by gnestor** [comment]
@JLCCI I am the most recent maintainer of this repo. I haven't been able to reproduce the installation issues described here although I can see it's affecting several users. Like you said, I haven't had time to fully investigate these issues. My intention is to eventually port nteract (an Electron-based Jupyter notebook client) to Atom because nteract's implementation is far more stable than this one. In the meantime, I suggest you use [nteract](https://github.com/nteract/nteract/) or the official [Jupyter Notebook](https://github.com/jupyter/notebook). Additionally, keep an eye out for [JupyterLab](https://github.com/jupyter/roadmap#next1-50) in the coming months.

**Comment by kingjr** [comment]
@gnestor you can reproduce the error on a fresh ubuntu 14.04 install. Here's what I get with a t2.micro aws:

```
sudo add-apt-repository ppa:webupd8team/atom
sudo apt-get update
sudo apt-get install atom
sudo apt-get install python python-pip
pip install jupyter jupyter_kernel_gateway  # error need sudo ?!
sudo pip install jupyter jupyter_kernel_gateway  # error need Python.h ?!
sudo apt-get install python3 python-pip
pip install jupyter jupyter_kernel_gateway
apm install jupyter-notebook

>>  ... nan.h error ...
```

**Comment by JLCCI** [comment]
@gnestor Thanks for the update, looking forward to your port of nteract!
