### ISSUE TITLE
Could not open file. TypeError: can not read property 'cells' of null

### ISSUE THREAD

**Issue by hugeme** [jupyter/atom-notebook#42]
Hi,

I have issues open an. `.ipynb` . I followed installation instructions and determined path to `jupyther`. But when I hit ' alt-cmd-o' via `advanced-open-file` I'll get `Could not open file. TypeError: can not read property 'cells' of null`. Opening a new file and saving it as `.ipynb` doesnt initiate the package as well. `Hydrogen`for example works well so I assumed the set up is correct. Appreciate any help!

`OSX El Capitan
10.11.4
Atom 1.6.2`

**Comment by kepbod** [comment]
Same errors when enter `atom a.ipynb`. `a.ipynb` is an empty file.

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [jupyter-notebook](https://github.com/jupyter/atom-notebook) package, v0.0.9


### Stack Trace

Uncaught TypeError: Cannot read property 'cells' of null

```
At /Users/zhangxiaoou/.atom/packages/jupyter-notebook/lib/notebook-editor.js:218

TypeError: Cannot read property 'cells' of null
    at NotebookEditor.loadNotebookFile (/Users/zhangxiaoou/.atom/packages/jupyter-notebook/lib/notebook-editor.js:218:21)
    at new NotebookEditor (/Users/zhangxiaoou/.atom/packages/jupyter-notebook/lib/notebook-editor.js:34:12)
    at openURI (/Users/zhangxiaoou/.atom/packages/jupyter-notebook/lib/main.js:90:80)
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:489:22)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:424:19)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1125:19)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:244:18)
    at emitThree (events.js:102:20)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "autocomplete-plus",
      "git-plus"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-go, v1.0.6
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.2
builder-go, v1.0.0
file-icons, v1.7.4
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
jupyter-notebook, v0.0.9
linter, v1.11.4
linter-flake8, v1.13.0
minimap, v4.22.1
navigator-godef, v1.0.2
tester-go, v1.0.4
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by hugeme** [comment]
@kepbod Have you resolved your problem?

**Comment by kepbod** [comment]
@hugeme I did not solve this problem yet.

**Comment by gnestor** [comment]
This repo is not being actively maintained 🙁 In the meantime, I suggest that you look at [hydrogen](https://github.com/nteract/hydrogen) to run code inline in Atom's text editor, [nteract](https://github.com/nteract/nteract) (a new Jupyter notebook client built using Electron, React, Redux, RxJS), [Jupyter Notebook](https://github.com/jupyter/notebook), and [JupyterLab](https://github.com/jupyterlab/jupyterlab). 

Having said that, nteract is currently extracting its many components into separate packages which will allow them to be reused and assembled to create new apps. When I have the time, I would like to use them to completely refactor this project.
