### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by kescobo** [jupyter/atom-notebook#47]
Attempted to open a .ipynb file when there was a git merge conflict (I'm using an atom plugin to resolve merge conflicts) but this error was thrown and would even allow the file to be opened. I was able to disable `atom-notebook` and open the file to resolve the conflict, then everything was fine. 

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.5
**Thrown From**: [jupyter-notebook](https://github.com/jupyter/atom-notebook) package, v0.0.9
### Stack Trace

Uncaught SyntaxError: Unexpected token <

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%22%2FUsers%2FKBLaptop%2Fcomputation%2FScience%2Fgender-comp-bio%22%5D%2C%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2FKBLaptop%2Fcomputation%2FScience%2Fgender-comp-bio%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%2C%22forceAddToWindow%22%3Afalse%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22env%22%3A%7B%22TMPDIR%22%3A%22%2Fvar%2Ffolders%2Fmv%2Fw3flyjvn7vnbllysvzrf9y480000gn%2FT%2F%22%2C%22__CF_USER_TEXT_ENCODING%22%3A%220x1F5%3A0x0%3A0x0%22%2C%22HOME%22%3A%22%2FUsers%2FKBLaptop%22%2C%22SHELL%22%3A%22%2Fbin%2Fbash%22%2C%22Apple_PubSub_Socket_Render%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.areGJfzWMt%2FRender%22%2C%22SSH_AUTH_SOCK%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.YvHbRsU481%2FListeners%22%2C%22PATH%22%3A%22%2Fusr%2Fbin%3A%2Fbin%3A%2Fusr%2Fsbin%3A%2Fsbin%22%2C%22LOGNAME%22%3A%22KBLaptop%22%2C%22XPC_SERVICE_NAME%22%3A%22com.github.atom.317792%22%2C%22COMMAND_MODE%22%3A%22unix2003%22%2C%22USER%22%3A%22KBLaptop%22%2C%22XPC_FLAGS%22%3A%220x0%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22ATOM_HOME%22%3A%22%2FUsers%2FKBLaptop%2F.atom%22%7D%2C%22appVersion%22%3A%221.7.3%22%2C%22atomHome%22%3A%22%2FUsers%2FKBLaptop%2F.atom%22%2C%22shellLoadTime%22%3A417%7D:2

SyntaxError: Unexpected token <
    at Object.parse (native)
    at NotebookEditor.parseNotebookFile (/Users/KBLaptop/.atom/packages/jupyter-notebook/lib/notebook-editor.js:243:19)
    at NotebookEditor.loadNotebookFile (/Users/KBLaptop/.atom/packages/jupyter-notebook/lib/notebook-editor.js:217:29)
    at new NotebookEditor (/Users/KBLaptop/.atom/packages/jupyter-notebook/lib/notebook-editor.js:34:12)
    at openURI (/Users/KBLaptop/.atom/packages/jupyter-notebook/lib/main.js:90:80)
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:489:22)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:424:19)
    at TreeView.module.exports.TreeView.entryClicked (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:476:28)
    at tree-view-file.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:188:26)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by gnestor** [comment]
This repo is not being actively maintained 🙁 In the meantime, I suggest that you look at [hydrogen](https://github.com/nteract/hydrogen) to run code inline in Atom's text editor, [nteract](https://github.com/nteract/nteract) (a new Jupyter notebook client built using Electron, React, Redux, RxJS), [Jupyter Notebook](https://github.com/jupyter/notebook), and [JupyterLab](https://github.com/jupyterlab/jupyterlab). 

Having said that, nteract is currently extracting its many components into separate packages which will allow them to be reused and assembled to create new apps. When I have the time, I would like to use them to completely refactor this project.
