### ISSUE TITLE
Cannot install on Mac

### ISSUE THREAD

**Issue by zhuzelong** [jupyter/atom-notebook#5]
OS: Mac OS X 10.10.4
Atom: latest

I clone the project in `~/Downloads` and then `cd` to the directory and `apm install` but error popped up.

```
runas@2.0.0 install /Users/Zack/Downloads/atom-notebook/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

  CXX(target) Release/obj.target/runas/src/main.o
  CXX(target) Release/obj.target/runas/src/runas_darwin.o
  CXX(target) Release/obj.target/runas/src/fork.o
  SOLINK_MODULE(target) Release/runas.node
  SOLINK_MODULE(target) Release/runas.node: Finished

> zmq@2.12.0 install /Users/Zack/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq
> node-gyp rebuild


> pathwatcher@4.4.3 install /Users/Zack/Downloads/atom-notebook/node_modules/pathwatcher
> node-gyp rebuild

  CXX(target) Release/obj.target/pathwatcher/src/main.o
  CXX(target) Release/obj.target/pathwatcher/src/common.o
  CXX(target) Release/obj.target/pathwatcher/src/handle_map.o
  CXX(target) Release/obj.target/pathwatcher/src/pathwatcher_mac.o
  SOLINK_MODULE(target) Release/pathwatcher.node
  SOLINK_MODULE(target) Release/pathwatcher.node: Finished

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Zack/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

npm ERR! Darwin 14.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/Zack/.atom/.apm/.apmrc" "--userconfig" "/Users/Zack/.atom/.apmrc" "install" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.12.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.12.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Zack/Downloads/atom-notebook/npm-debug.log
```

**Comment by willwhitney** [comment]
It sounds like this is the issue described here: https://github.com/TooTallNate/node-gyp/issues/341 with a workaround here: https://github.com/TooTallNate/node-gyp/issues/341#issuecomment-73983623. Doing a full install of XCode also seems to work, but is major overkill.

Since this is an issue upstream, I'm going to close this issue. However, we're definitely working to remove this dependency.
