### ISSUE TITLE
Uncaught TypeError: Cannot read property 'null' of undefined

### ISSUE THREAD

**Issue by Vvkmnn** [jupyter/atom-notebook#50]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.5
**Thrown From**: [jupyter-notebook](https://github.com/jupyter/atom-notebook) package, v0.0.9

### Stack Trace

Uncaught TypeError: Cannot read property 'null' of undefined

```
At /Users/vivek.menon/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactMount.js:649

TypeError: Cannot read property 'null' of undefined
    at Object.ReactMount.findReactContainerForID (/Users/vivek.menon/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactMount.js:649:50)
    at findParent (/Users/vivek.menon/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactEventListener.js:41:30)
    at handleTopLevelWithoutPath (/Users/vivek.menon/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactEventListener.js:87:16)
    at handleTopLevelImpl (/Users/vivek.menon/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactEventListener.js:73:3)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/vivek.menon/.atom/packages/jupyter-notebook/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/vivek.menon/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.batchedUpdates (/Users/vivek.menon/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactUpdates.js:94:20)
    at ReactEventListener.dispatchEvent (/Users/vivek.menon/.atom/packages/jupyter-notebook/node_modules/react/lib/ReactEventListener.js:204:20)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "openEmptyEditorOnStart": false,
    "projectHome": "~/Dropbox",
    "themes": [
      "seti-ui",
      "dracula-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
autocomplete-python, v1.4.3
dracula-theme, v1.2.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
jupyter-notebook, v0.0.9
linter, v1.11.3
linter-flake8, v1.9.3
minimap, v4.19.0
open-recent, v4.0.1
release-notes, v0.53.0
seti-ui, v0.8.1
sync-settings, v0.7.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by draperjames** [comment]
I'm having the same issues here. @Vvkmnn have you had any luck with this?

**Comment by gnestor** [comment]
This repo is not being actively maintained 🙁 In the meantime, I suggest that you look at [hydrogen](https://github.com/nteract/hydrogen) to run code inline in Atom's text editor, [nteract](https://github.com/nteract/nteract) (a new Jupyter notebook client built using Electron, React, Redux, RxJS), [Jupyter Notebook](https://github.com/jupyter/notebook), and [JupyterLab](https://github.com/jupyterlab/jupyterlab). 

Having said that, nteract is currently extracting its many components into separate packages which will allow them to be reused and assembled to create new apps. When I have the time, I would like to use them to completely refactor this project.
