### ISSUE TITLE
`Installing “jupyter-notebook@0.0.9” failed.` (El Capitan 

### ISSUE THREAD

**Issue by jolespin** [jupyter/atom-notebook#54]
```
Installing “jupyter-notebook@0.0.9” failed.Hide output…

> runas@3.1.1 install /private/var/folders/6z/5vbtz_gmkr76ftgc3149dvtr0003c0/T/apm-install-dir-116712-2921-xjfu5u/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild


> bufferutil@1.2.1 install /private/var/folders/6z/5vbtz_gmkr76ftgc3149dvtr0003c0/T/apm-install-dir-116712-2921-xjfu5u/node_modules/jupyter-notebook/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild


> utf-8-validate@1.2.1 install /private/var/folders/6z/5vbtz_gmkr76ftgc3149dvtr0003c0/T/apm-install-dir-116712-2921-xjfu5u/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild


gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:119:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/6z/5vbtz_gmkr76ftgc3149dvtr0003c0/T/apm-install-dir-116712-2921-xjfu5u/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:119:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:979:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:466:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/6z/5vbtz_gmkr76ftgc3149dvtr0003c0/T/apm-install-dir-116712-2921-xjfu5u/node_modules/jupyter-notebook/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:119:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:979:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:466:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/6z/5vbtz_gmkr76ftgc3149dvtr0003c0/T/apm-install-dir-116712-2921-xjfu5u/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm ERR! Darwin 15.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jespinoz/.atom/.apm/.apmrc" "--userconfig" "/Users/jespinoz/.atom/.apmrc" "install" "/private/var/folders/6z/5vbtz_gmkr76ftgc3149dvtr0003c0/T/d-116712-2921-eoc6aa/package.tgz" "--target=0.37.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/6z/5vbtz_gmkr76ftgc3149dvtr0003c0/T/apm-install-dir-116712-2921-xjfu5u/npm-debug.log
```

**Comment by jolespin** [comment]
Has anyone got this to work for `El Capitan`, `Atom 1.9.8`, and `Jupyter 4.1.0`?

**Comment by fluency03** [comment]
same problem, but under window 7

**Comment by ShupingR** [comment]
Same problem Max El Capitan

**Comment by fluency03** [comment]
@ShupingR I am using python 2

**Comment by jolespin** [comment]
Hopefully we can get this working soon.  It would be cool to work out of Atom instead of the browser.

**Comment by postalbyke** [comment]
I have this problem also. Is there a way to update the gyp component to work with newer versions of Python?

**Comment by BenseddikM** [comment]
same problem here... not running on python 3, please an update to fix it :)

**Comment by lightingghost** [comment]
same here

**Comment by rancherobeans** [comment]
Same problem here. My error message:

Installing “jupyter-notebook@0.0.9” failed.Hide output…

> bufferutil@1.2.1 install /private/var/folders/n5/yyyx198j57ddwx7pvx7yw5_r0000gn/T/apm-install-dir-11709-4248-1hv3w2n/node_modules/jupyter-notebook/node_modules/bufferutil
> node-gyp rebuild


> runas@3.1.1 install /private/var/folders/n5/yyyx198j57ddwx7pvx7yw5_r0000gn/T/apm-install-dir-11709-4248-1hv3w2n/node_modules/jupyter-notebook/node_modules/runas
> node-gyp rebuild

/private/var/folders/n5/yyyx198j57ddwx7pvx7yw5_r0000gn/T/apm-install-dir-11709-4248-1hv3w2n
└── (empty)


gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/mchana/anaconda3/bin/python" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:477:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/n5/yyyx198j57ddwx7pvx7yw5_r0000gn/T/apm-install-dir-11709-4248-1hv3w2n/node_modules/jupyter-notebook/node_modules/bufferutil
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/mchana/anaconda3/bin/python" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:477:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/n5/yyyx198j57ddwx7pvx7yw5_r0000gn/T/apm-install-dir-11709-4248-1hv3w2n/node_modules/jupyter-notebook/node_modules/runas
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/n5/yyyx198j57ddwx7pvx7yw5_r0000gn/T/apm-install-dir-11709-4248-1hv3w2n/package.json'
npm WARN apm-install-dir-11709-4248-1hv3w2n No description
npm WARN apm-install-dir-11709-4248-1hv3w2n No repository field.
npm WARN apm-install-dir-11709-4248-1hv3w2n No README data
npm WARN apm-install-dir-11709-4248-1hv3w2n No license field.
npm ERR! Darwin 16.1.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mchana/.atom/.apm/.apmrc" "--userconfig" "/Users/mchana/.atom/.apmrc" "install" "/private/var/folders/n5/yyyx198j57ddwx7pvx7yw5_r0000gn/T/d-11709-4248-zw67lv/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/n5/yyyx198j57ddwx7pvx7yw5_r0000gn/T/apm-install-dir-11709-4248-1hv3w2n/npm-debug.log
npm ERR! code 1

**Comment by swdrsk** [comment]
I have same problem,
My environment is below:

OS: Windows10 64bit
Python: 2.7.12 (under anaconda)
Atom: 1.13.0
===
$ conda list | grep jupyter
jupyter                   1.0.0                    py27_3
jupyter-kernel-gateway    1.1.2                     <pip>
jupyter_client            4.4.0                    py27_0
jupyter_console           5.0.0                    py27_0
jupyter_core              4.2.0                    py27_0
jupyterlab                0.11.2                    <pip>

**Comment by rithwikjc** [comment]
Same problem, different error message. Based on what I could infer from what I read elsewhere it is because I have python 3.x installed on my PC and not python 2.x.
```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\Rithwik\\AppData\\Local\\atom\\app-1.13.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Rithwik\\AppData\\Local\\atom\\app-1.13.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Rithwik\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Rithwik\\.atom\\.apmrc" "install" "C:\\Users\\Rithwik\\AppData\\Local\\Temp\\d-11713-5468-123khu3\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code EREADFILE

npm ERR! Error extracting C:\Users\Rithwik\.atom\.apm\pathwatcher\6.7.1\package.tgz archive: ENOENT: no such file or directory, open 'C:\Users\Rithwik\.atom\.apm\pathwatcher\6.7.1\package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Rithwik\AppData\Local\Temp\apm-install-dir-11713-5468-1q6ck1n\npm-debug.log
```

**Comment by aufdenkampe** [comment]
Same problem, on MacOS 10.12.3, Python 2.7.13 |Anaconda 4.3.0 (x86_64)
On this machine, I installed Anaconda Python for all users, so that my Python path is here: //anaconda/bin/

On my home Mac this installed fine. It's the same OS & Python, but I installed just for me. I'm concerned that there is a path or permissions issue, but I can't figure it out. 
Any ideas?

**Comment by IreneCrisologo** [comment]
Same problem, Windows 8, installation attempt via Atom Install Packages.

**Comment by gnestor** [comment]
This repo is not being actively maintained 🙁 In the meantime, I suggest that you look at [hydrogen](https://github.com/nteract/hydrogen) to run code inline in Atom's text editor, [nteract](https://github.com/nteract/nteract) (a new Jupyter notebook client built using Electron, React, Redux, RxJS), [Jupyter Notebook](https://github.com/jupyter/notebook), and [JupyterLab](https://github.com/jupyterlab/jupyterlab). 

Having said that, nteract is currently extracting its many components into separate packages which will allow them to be reused and assembled to create new apps. When I have the time, I would like to use them to completely refactor this project.
