### ISSUE TITLE
Package not working

### ISSUE THREAD

**Issue by spencerlyon2** [jupyter/atom-notebook#6]
[Enter steps to reproduce below:]

1. install (`git clone ...` then `PYTHON=python2.6 apm install` then `apm link`)
2. start atom with `PYTHON=python2.6 atom` *or*  use default python and just use `atom` (I tried both)
3. Then try to open any .ipynb file

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [jupyter-notebook](https://github.com/willwhitney/jupyter-notebook-atom) package, v0.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

```
At /Users/sglyon/src/atom/atom-notebook/lib/text-editor.js:26

TypeError: Cannot read property 'toLowerCase' of undefined
  at /Users/sglyon/src/atom/atom-notebook/lib/text-editor.js:74:36
  at Array.filter (native)
  at Function.getGrammarForLanguage (/Users/sglyon/src/atom/atom-notebook/lib/text-editor.js:73:59)
  at Editor.componentDidMount (/Users/sglyon/src/atom/atom-notebook/lib/text-editor.js:45:34)
  at CallbackQueue.assign.notifyAll (/Users/sglyon/src/atom/atom-notebook/node_modules/react/lib/CallbackQueue.js:68:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Users/sglyon/src/atom/atom-notebook/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
  at ReactReconcileTransaction.Mixin.closeAll (/Users/sglyon/src/atom/atom-notebook/node_modules/react/lib/Transaction.js:207:25)
  at ReactReconcileTransaction.Mixin.perform (/Users/sglyon/src/atom/atom-notebook/node_modules/react/lib/Transaction.js:148:16)
  at batchedMountComponentIntoNode (/Users/sglyon/src/atom/atom-notebook/node_modules/react/lib/ReactMount.js:269:15)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/sglyon/src/atom/atom-notebook/node_modules/react/lib/Transaction.js:134:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/sglyon/src/atom/atom-notebook/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
  at Object.batchedUpdates (/Users/sglyon/src/atom/atom-notebook/node_modules/react/lib/ReactUpdates.js:110:20)
  at Object.ReactMount._renderNewRootComponent (/Users/sglyon/src/atom/atom-notebook/node_modules/react/lib/ReactMount.js:404:18)
  at Object.ReactMount.render (/Users/sglyon/src/atom/atom-notebook/node_modules/react/lib/ReactMount.js:493:32)
  at Object.createView (/Users/sglyon/src/atom/atom-notebook/lib/main.js:26:43)
  at ViewRegistry.module.exports.ViewRegistry.createView (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/src/view-registry.js:80:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/src/view-registry.js:65:21)
  at atom-pane.PaneElement.getActiveView (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/src/pane-element.js:210:25)
  at atom-pane.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/src/pane-element.js:60:55)
  at atom-pane.PaneElement.activated (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/src/pane-element.js:125:19)
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.activate (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/src/pane.js:639:27)
  at Immediate._onImmediate (/opt/homebrew-cask/Caskroom/atom/1.0.11/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:212:33)
  at processImmediate [as _immediateCallback] (timers.js:371:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/sglyon",
    "disabledPackages": [
      "wrap-guide",
      "language-scala",
      "todo-list",
      "racer",
      "markdown-preview"
    ],
    "themes": [
      "isotope-ui",
      "tomorrow-night-eighties-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-alignment, v0.12.1
atom-spotify2, v2.1.2
atomatigit, v1.5.4
autocomplete-bibtex, v0.6.1
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
autocomplete-python, v0.6.2
build, v0.47.0
build-make, v0.2.1
file-icons, v1.6.10
file-types, v0.5.1
floobits, v0.21.1
fonts, v0.6.1
imdone-atom, v1.1.45
ink, v0.1.1
isotope-ui, v2.5.2
jupyter-notebook, v0.0.1
language-diff, v0.3.1
language-fortran, v2.0.0
language-haskell, v1.4.11
language-julia, v0.4.1
language-latex, v0.6.1
language-matlab, v0.1.1
language-pfm, v0.82.0
language-r, v0.3.0
language-rust, v0.4.5
last-cursor-position, v0.9.0
latex, v0.26.0
latex-completions, v0.3.0
latexer, v0.2.7
linter, v1.8.1
linter-flake8, v1.9.0
linter-rust, v0.2.9
markdown-preview-plus, v2.2.1
mathjax-wrapper, v0.1.0
minimap, v4.13.4
minimap-git-diff, v4.1.8
multi-wrap-guide, v0.22.3
pdf-view, v0.32.0
project-manager, v2.6.3
selection-counter, v1.0.0
time-status, v1.1.0
tomorrow-night-eighties-syntax, v0.6.1
tool-bar, v0.1.9
vim-mode, v0.61.0
vim-surround, v0.8.0
wakatime, v5.0.0

# Dev
No dev packages
```

**Comment by willwhitney** [comment]
Closed by #7.
