### ISSUE TITLE
Uncaught SyntaxError: Unexpected token i in JSON at position 0

### ISSUE THREAD

**Issue by 95ellismle** [jupyter/atom-notebook#64]
[Enter steps to reproduce:]

1. Created a file named "plotter.ipynb"
2. Tried Opening the Jupyter Notebook package returned this error

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [jupyter-notebook](https://github.com/jupyter/atom-notebook) package 0.0.9

### Stack Trace

Uncaught SyntaxError: Unexpected token i in JSON at position 0

```
At file:///usr/share/atom/resources/app.asar/static/index.html:1

SyntaxError: Unexpected token i in JSON at position 0
    at Object.parse (native)
    at NotebookEditor.parseNotebookFile (/packages/jupyter-notebook/lib/notebook-editor.js:243:19)
    at NotebookEditor.loadNotebookFile (/packages/jupyter-notebook/lib/notebook-editor.js:217:29)
    at /packages/jupyter-notebook/lib/notebook-editor.js:34:12)
    at openURI (/packages/jupyter-notebook/lib/main.js:90:80)
    at Workspace.module.exports.Workspace.openURIInPane (/app.asar/src/workspace.js:501:22)
    at Workspace.module.exports.Workspace.open (/app.asar/src/workspace.js:436:19)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/app.asar/src/atom-environment.js:1187:18)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:229:18)
    at emitThree (events.js:121:20)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:44.8.0 core:backspace (input.hidden-input)
     -1:43.7.0 intentions:highlight (input.hidden-input)
     -1:43.4.0 editor:newline-above (input.hidden-input)
     -1:42.7.0 core:backspace (input.hidden-input)
     -1:42.2.0 core:delete (input.hidden-input)
     -1:29.4.0 editor:newline (input.hidden-input)
     -1:26.7.0 intentions:highlight (input.hidden-input)
     -1:26.4.0 editor:newline-above (input.hidden-input)
     -1:21.3.0 intentions:show (input.hidden-input)
     -1:18.9.0 core:delete (input.hidden-input)
     -1:17.3.0 intentions:highlight (input.hidden-input)
     -1:17 symbols-view:toggle-file-symbols (input.hidden-input)
     -1:15.8.0 intentions:highlight (input.hidden-input)
     -1:15.5.0 symbols-view:toggle-project-symbols (input.hidden-input)
  2x -1:14.4.0 intentions:highlight (input.hidden-input)
     -1:12.5.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
atom-snowball-syntax-theme 0.0.1 
busy-signal 1.3.0 
gpp-compiler 3.0.7 
highlight-selected 0.13.1 
highlight-words-syntax 0.0.0 
intentions 1.1.2 
jupyter-notebook 0.0.9 
linter 2.1.2 
linter-gcc 0.7.1 
linter-ui-default 1.2.2 
minimap 4.27.1 
minimap-highlight-selected 4.6.1 
script 3.14.1 
```

**Comment by fbrundu** [comment]
This repo is not actively maintained at the moment, see [this comment](https://github.com/jupyter/atom-notebook/issues/62#issuecomment-282502603).
