### ISSUE TITLE
"Failed to load the jupyter-notebook package" on Atom 1.18

### ISSUE THREAD

**Issue by mkals** [jupyter/atom-notebook#67]
Hello, 

I get this same error message, both when  installing directly through GitHub as described [here](https://github.com/jupyter/atom-notebook/issues/8) and when going through the plugin manager. 

Is there a trick I could do to make it work? Any help would be greatly appreciated!  

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [jupyter-notebook](https://github.com/jupyter/atom-notebook) package 0.0.10

### Stack Trace

Failed to load the jupyter-notebook package

```
At /Users/mKals/.atom/packages/jupyter-notebook/lib/main.js: Unexpected token (36:4)

SyntaxError: /Users/mKals/.atom/packages/jupyter-notebook/lib/main.js: Unexpected token (36:4)
        return el;
      }
    });
  },

  deactivate() {
    at Parser.pp.raise (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.expect (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/util.js:76:33)
    at Parser.pp.parseExprList (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:785:12)
    at Parser.pp.parseSubscripts (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:270:29)
    at Parser.pp.parseExprSubscripts (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:240:17)
    at Parser.pp.parseMaybeUnary (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExpression (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:79:19)
    at Parser.pp.parseStatement (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/statement.js:137:23)
    at Parser.parseStatement (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseBlock (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/statement.js:442:21)
    at Parser.pp.parseFunctionBody (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:747:22)
    at Parser.parseFunctionBody (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/plugins/flow.js:643:20)
    at Parser.pp.parseMethod (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:717:8)
    at Parser.pp.parseObjPropValue (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:658:23)
    at Parser.parseObjPropValue (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/plugins/flow.js:891:13)
    at Parser.pp.parseObj (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:640:10)
    at Parser.pp.parseExprAtom (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:392:19)
    at Parser.parseExprAtom (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExport (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/statement.js:682:21)
    at Parser.parseExport (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/plugins/flow.js:713:20)
    at Parser.pp.parseStatement (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/statement.js:115:90)
    at Parser.parseStatement (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseTopLevel (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/statement.js:30:21)
    at Parser.parse (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/parser/index.js:70:17)
    at Object.parse (/Applications/Atom.app/Contents/Resources/app/node_modules/babylon/lib/index.js:45:50)
    at Object.exports.default (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/helpers/parse.js:36:18)
    at File.parse (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/file/index.js:574:40)
    at File.parseCode (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/file/index.js:691:20)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/pipeline.js:167:12
    at File.wrap (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/file/index.js:639:16)
    at Pipeline.transform (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
    at Object.exports.compile (/Applications/Atom.app/Contents/Resources/app/src/babel.js:70:22)
    at Object.compile (/Applications/Atom.app/Contents/Resources/app/src/package-transpilation-registry.js:79:33)
    at compileFileAtPath (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:97:37)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:238:26)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:565:22)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:495:27)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:521:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -2:04.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-xcode-theme.theme-atom-light-ui)
     -1:40.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
autocomplete-clang 0.11.3 
busy-signal 1.4.3 
cpp-generator 0.1.0 
ex-mode 0.15.0 
Hydrogen 1.18.0 
intentions 1.1.2 
jupyter-notebook 0.0.10 
linter 2.2.0 
linter-clang 4.1.1 
linter-ui-default 1.6.2 
markdown-preview-plus 2.4.9 
vim-mode-plus 0.93.0 
xcode-theme 1.4.0 
```

**Comment by gautam1858** [comment]
Me too

**Comment by nsalerni** [comment]
Same here.

**Comment by DostalJ** [comment]
Me too

**Comment by xxf1995** [comment]
same

**Comment by nasyxx** [comment]
same

**Comment by louismartin** [comment]
Up, same, me too

**Comment by maricar-m** [comment]
same

**Comment by vlaskinvlad** [comment]
+1

**Comment by richtrf** [comment]
+1

**Comment by nicholasbutlin** [comment]
+1

**Comment by rafa2000** [comment]
+1

**Comment by wikp** [comment]
Bump

**Comment by salehmoe** [comment]
+1

**Comment by xiligey** [comment]
+1

**Comment by pant03** [comment]
+1

**Comment by PunkFood-Disme** [comment]
+1

**Comment by dalegebit** [comment]
+2

**Comment by dalegebit** [comment]
Oh, simply remove the '}' at that line can get rid of the exception, but after doing so the layout get really ugly

**Comment by salehmoe** [comment]
How to remove the '}'

**Comment by maxhodak** [comment]
Any update?

**Comment by tdrobbin** [comment]
+1

**Comment by mallen5311** [comment]
+1

**Comment by all3fox** [comment]
bumpy bump

**Comment by valmormn** [comment]
wtf?!?

**Comment by rlbc** [comment]
+1

**Comment by adkinsty** [comment]
+1

**Comment by marskar** [comment]
+1

**Comment by moonbury** [comment]
+1

**Comment by anandharidass** [comment]
+1

**Comment by kibernick** [comment]
+1

**Comment by naveensr89** [comment]
+1

**Comment by SumNeuron** [comment]
When do they want to address this?

**Comment by kingwyf87** [comment]
Please try to delete `{` in the `main.js` file as mentioned #68  You should be able to find this file here: `/Users/USERNAME/.atom/packages/jupyter-notebook/lib` This will fix this issue.

**Comment by valmormn** [comment]
At line 34 In main.js at /home/$USER/.atom/packages/jupyter-notebook/lib

```
activate(state) {
    // console.log('Activated');
    fixPath();
    this.openerDisposable = atom.workspace.addOpener(openURI);
    this.commands = atom.commands.add('.notebook-cell atom-text-editor', 'jupyter-notebook-atom:run', this.run);
    atom.views.addViewProvider(NotebookEditor,
      model => {
        let el = document.createElement('div');
        el.classList.add('notebook-wrapper');
        let viewComponent = ReactDOM.render(<NotebookEditorView store={model} />, el);
        return el;
      }
    }); //  *** delete this curly bracer at the begining of line ***
  },
```

**Comment by Nic-Nic** [comment]
+1

**Comment by me1er** [comment]
+1

**Comment by alexBeuth** [comment]
+1

**Comment by AdrienMereghetti** [comment]
+1

**Comment by smoge** [comment]
+1

**Comment by rukmal** [comment]
+1

**Comment by dogaker** [comment]
+1

**Comment by benjavides** [comment]
+1

**Comment by RossKen** [comment]
+1

**Comment by KevinHu2014** [comment]
+1

**Comment by matthewswallace** [comment]
++1 ... that was such an easy fix. someone needs to issue a PR for this and get it merged already.

**Comment by Lijia-Li** [comment]
++

**Comment by erdemalpkaya** [comment]
+

**Comment by tandriamil** [comment]
Now the error message is gone and so did the design of the notebook ... rip  :cry:

**Comment by wadekun** [comment]
++

**Comment by dnflakwd** [comment]
+1

**Comment by burkesquires** [comment]
+1

**Comment by jaredtconnor** [comment]
+1 to getting this same issue. I do believe the package is lacking maintainers though, so we might be out of luck. 

If anyone is still looking for a jupyter like development environment, check out [Hydrogen](https://atom.io/packages/hydrogen). It's a great way in Atom to run snippets scripts and print graphs, results, tables, etc.

**Comment by dvictori** [comment]
After this change, the plugging loads fine but now the layout of the notebook is all messed up. Anyone having the same issue?

**Comment by DannyDannyDanny** [comment]
+1

**Comment by bunnyhole** [comment]
+1

**Comment by r3dang** [comment]
layout is ruined :(

**Comment by gnestor** [comment]
FYI, this project is deprecated:

> This project does not have any active maintainers. We recommend that you use nteract, a native notebook application built using Electron, React (like this project), Redux, and RxJS, or Hydrogen, a LightTable-inspired package for Atom that allows users to run code blocks and selections using Jupyter kernels.

If anyone would like to become maintainer of this repo, let me know and I'll spend some time introducing you to the codebase.

**Comment by sushinoya** [comment]
@gnestor I would not mind. why did the maintainers decide to let it go though?

**Comment by DraceniY** [comment]
+1

**Comment by gnestor** [comment]
Well I was the only one maintaining it and then I got contracted to work on Jupyter Notebook and JupyterLab, both of which the org has grants for. Unfortunately, no one is funding atom-notebook development at the moment. I was really excited about it at the time, but since then, hydrogen (use Jupyter backend to evaluate code inline in Atom), nteract (native Jupyter notebook app using Electron), JupyterLab Native (native JupyterLab app using Electron), and JupyterLab (the next-generation Jupyter client) have emerged. I would give hydrogen and good look before diving into this because it's built on strong foundations and it fits really well into the Atom workflow.

**Comment by sushinoya** [comment]
I'll definitely look into Hydrogen :) @gnestor is there a way to be using Atom shortcuts in JupyterLab?

**Comment by gnestor** [comment]
There are currently vim, emac, and Sublime Text keymap bindings in JupyterLab:

![image](https://user-images.githubusercontent.com/512354/38287388-49d62902-377f-11e8-8e79-a54bc246d000.png)

**Comment by flios** [comment]
+1

**Comment by MesiA** [comment]
is it rude to say "Me too" ?!

**Comment by Dooori** [comment]
same issue here

**Comment by phaabe** [comment]
wow! me too. Seems like this project is dead :/

**Comment by gnestor** [comment]
Ya, dead until we can find a maintainer. Check out Hydrogen!

**Comment by laurentperrinet** [comment]
> is it rude to say "Me too" ?!

#MeToo

**Comment by brandonsimpson21** [comment]
error still exists, atom says "issue reported" and links here after failure

**Comment by SamDingore** [comment]
There is a extra `} `in the main .js file
Simply open file : /home/.atom/packages/jupyter-notebook/lib/main.js
inside main.js on line 36: `});` Replace this with` )},` and On line 37 or 38 there is a `}, `remove it
Save the file
restart Atom

**Comment by F1nalFortune** [comment]
> There is a extra `} `in the main .js file Simply open file : /home/.atom/packages/jupyter-notebook/lib/main.js inside main.js on line 36: `});` Replace this with` )},` and On line 37 or 38 there is a `}, `remove it Save the file restart Atom

Windows path for me was `C:\Users\<username>\.atom\packages\jupyter-notebook\lib\main.js`
