### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by dayvidwesley** [jupyter/atom-notebook#70]
(Mac OS High Sierra )

Installing “jupyter-notebook@0.0.10” failed.Hide output…

> bufferutil@1.2.1 install /private/var/folders/5n/1pnhd3t94ws8lnj_vp3wnwpm0000gn/T/apm-install-dir-1171010-1369-1moyeiv.iu4dmo0f6r/node_modules/jupyter-notebook/node_modules/bufferutil
> node-gyp rebuild

> runas@3.1.1 install /private/var/folders/5n/1pnhd3t94ws8lnj_vp3wnwpm0000gn/T/apm-install-dir-1171010-1369-1moyeiv.iu4dmo0f6r/node_modules/jupyter-notebook/node_modules/runas
> node-gyp rebuild

/private/var/folders/5n/1pnhd3t94ws8lnj_vp3wnwpm0000gn/T/apm-install-dir-1171010-1369-1moyeiv.iu4dmo0f6r
`-- (empty)

npm WARN deprecated jupyter-js-services@0.21.1: This package has moved to @jupyterlab/services
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 17.2.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/5n/1pnhd3t94ws8lnj_vp3wnwpm0000gn/T/apm-install-dir-1171010-1369-1moyeiv.iu4dmo0f6r/node_modules/jupyter-notebook/node_modules/bufferutil
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Darwin 17.2.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/5n/1pnhd3t94ws8lnj_vp3wnwpm0000gn/T/apm-install-dir-1171010-1369-1moyeiv.iu4dmo0f6r/node_modules/jupyter-notebook/node_modules/runas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/5n/1pnhd3t94ws8lnj_vp3wnwpm0000gn/T/apm-install-dir-1171010-1369-1moyeiv.iu4dmo0f6r/package.json'
npm WARN apm-install-dir-1171010-1369-1moyeiv.iu4dmo0f6r No description
npm WARN apm-install-dir-1171010-1369-1moyeiv.iu4dmo0f6r No repository field.
npm WARN apm-install-dir-1171010-1369-1moyeiv.iu4dmo0f6r No README data
npm WARN apm-install-dir-1171010-1369-1moyeiv.iu4dmo0f6r No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules/jupyter-notebook/node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Darwin 17.2.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/dayvidwesley/.atom/.apm/.apmrc" "--userconfig" "/Users/dayvidwesley/.atom/.apmrc" "install" "/private/var/folders/5n/1pnhd3t94ws8lnj_vp3wnwpm0000gn/T/d-1171010-1369-nmj6d0.g1gihk6gvi/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/5n/1pnhd3t94ws8lnj_vp3wnwpm0000gn/T/apm-install-dir-1171010-1369-1moyeiv.iu4dmo0f6r/npm-debug.log
npm ERR! code 1

**Comment by nikagra** [comment]
Same problem here. Atom 1.23.2 x64 Windows 10.

> Please include the following file with any support request
This file seems to be removed after failed installation attempt

**Comment by nikagra** [comment]
The problem might be due to Python version (3.6.3 in my case)

Does anyone know how to pass `-python` argument to `node-gyp rebuild`? I don't like to reinstall Python since I'm using current version of it

**Comment by nikagra** [comment]
@chauhan-utk Yep. I stopped using Atom. I propose you to use Python Jupyter Notebook directly (eventually even Intellij Idea have some support for (Jupyter Notebook). The problems with `node-gyp` are to deep and I have no time to solve them
