### ISSUE TITLE
Failed to activate the jupyter-notebook package

### ISSUE THREAD

**Issue by STsui1019** [jupyter/atom-notebook#71]
I just reinstalled atom-notebook and it cannot be launched anymore.

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [jupyter-notebook](https://github.com/jupyter/atom-notebook) package 0.0.10

### Stack Trace

Failed to activate the jupyter-notebook package

```
At /home/stephentsui/.atom/packages/jupyter-notebook/lib/main.js: Unexpected token (36:4)

SyntaxError: /home/stephentsui/.atom/packages/jupyter-notebook/lib/main.js: Unexpected token (36:4)
        return el;
      }
    });
  },

  deactivate() {
    at Parser.pp.raise (/app.asar/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/app.asar/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.expect (/app.asar/node_modules/babylon/lib/parser/util.js:76:33)
    at Parser.pp.parseExprList (/app.asar/node_modules/babylon/lib/parser/expression.js:785:12)
    at Parser.pp.parseSubscripts (/app.asar/node_modules/babylon/lib/parser/expression.js:270:29)
    at Parser.pp.parseExprSubscripts (/app.asar/node_modules/babylon/lib/parser/expression.js:240:17)
    at Parser.pp.parseMaybeUnary (/app.asar/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/app.asar/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/app.asar/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/app.asar/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExpression (/app.asar/node_modules/babylon/lib/parser/expression.js:79:19)
    at Parser.pp.parseStatement (/app.asar/node_modules/babylon/lib/parser/statement.js:137:23)
    at Parser.parseStatement (/app.asar/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseBlock (/app.asar/node_modules/babylon/lib/parser/statement.js:442:21)
    at Parser.pp.parseFunctionBody (/app.asar/node_modules/babylon/lib/parser/expression.js:747:22)
    at Parser.parseFunctionBody (/app.asar/node_modules/babylon/lib/plugins/flow.js:643:20)
    at Parser.pp.parseMethod (/app.asar/node_modules/babylon/lib/parser/expression.js:717:8)
    at Parser.pp.parseObjPropValue (/app.asar/node_modules/babylon/lib/parser/expression.js:658:23)
    at Parser.parseObjPropValue (/app.asar/node_modules/babylon/lib/plugins/flow.js:891:13)
    at Parser.pp.parseObj (/app.asar/node_modules/babylon/lib/parser/expression.js:640:10)
    at Parser.pp.parseExprAtom (/app.asar/node_modules/babylon/lib/parser/expression.js:392:19)
    at Parser.parseExprAtom (/app.asar/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/app.asar/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/app.asar/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/app.asar/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/app.asar/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/app.asar/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExport (/app.asar/node_modules/babylon/lib/parser/statement.js:682:21)
    at Parser.parseExport (/app.asar/node_modules/babylon/lib/plugins/flow.js:713:20)
    at Parser.pp.parseStatement (/app.asar/node_modules/babylon/lib/parser/statement.js:115:90)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
atom-ide-ui 0.5.4 
atom-python-run 0.9.3 
atom-runner 2.7.1 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
Hydrogen 2.0.1 
hydrogen-launcher 1.2.1 
ide-cpp 0.0.3 
ide-html 0.4.1 
ide-python 0.3.0 
intentions 1.1.5 
jupyter-notebook 0.0.10 
language-markdown 0.25.1 
linter 2.2.0 
linter-ui-default 1.6.10 
markdown-assistant 0.2.0 
markdown-pdf 2.1.0 
markdown-preview-plus 2.4.16 
markdown-scroll-sync 2.1.2 
markdown-table-editor 0.6.4 
markdown-toc 0.4.2 
markdown-writer 2.7.3 
python-debugger 0.2.0 
python-indent 1.1.4 
python-tools 0.6.9 
script-runner 2.2.1 
seti-icons 1.5.4 
sync-settings 0.8.3 
tidy-markdown 3.0.1 
```

**Comment by despairr** [comment]
The same problem with Atom: 1.22.1 on MacOSX

**Comment by MeTavi** [comment]
The same issue on MacOSX 10.13.2 (17C88) and ATOM 1.23.2.

**Comment by dvictori** [comment]
I think it's the same problem in #67

**Comment by brandonsimpson21** [comment]
i get the same error as #67 but it was closed without fixing :(

**Comment by brucebookman** [comment]
Folks, why is this still open?  First reported 2017

**Comment by aminya** [comment]
See https://github.com/jupyter/atom-notebook/issues/104#issuecomment-764612232

**Comment by maleksware** [comment]
> Folks, why is this still open? First reported 2017

This package is not deprecated but it has no support, so there is no people that can contribute to it.

**Comment by SamDingore** [comment]
There is a extra  `}`  in the main .js  file 
Simply open file : /home/.atom/packages/jupyter-notebook/lib/main.js 
inside main.js on line 36: ` });  `Replace this with `)},`  and On line 37 or 38 there is a `},  `remove it 
Save the file 
restart Atom

**Comment by dustykeyboard1** [comment]
The package still does not work for same error
