### ISSUE TITLE
Installation defaults to Python 3.6.4

### ISSUE THREAD

**Issue by TomGao2001** [jupyter/atom-notebook#72]
Installing “jupyter-notebook@0.0.10” failed.Hide output…

> bufferutil@1.2.1 install C:\Users\ZIMING~1\AppData\Local\Temp\apm-install-dir-118023-10792-ucb8rn.d37ssgu8fr\node_modules\jupyter-notebook\node_modules\bufferutil
> node-gyp rebuild

C:\Users\ZIMING~1\AppData\Local\Temp\apm-install-dir-118023-10792-ucb8rn.d37ssgu8fr\node_modules\jupyter-notebook\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Ziming Gao\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Ziming Gao\AppData\Local\atom\app-1.23.3\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

> runas@3.1.1 install C:\Users\ZIMING~1\AppData\Local\Temp\apm-install-dir-118023-10792-ucb8rn.d37ssgu8fr\node_modules\jupyter-notebook\node_modules\runas
> node-gyp rebuild

C:\Users\ZIMING~1\AppData\Local\Temp\apm-install-dir-118023-10792-ucb8rn.d37ssgu8fr\node_modules\jupyter-notebook\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\Ziming Gao\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Ziming Gao\AppData\Local\atom\app-1.23.3\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\ZIMING~1\AppData\Local\Temp\apm-install-dir-118023-10792-ucb8rn.d37ssgu8fr
`-- (empty)

npm WARN deprecated jupyter-js-services@0.21.1: This package has moved to @jupyterlab/services
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Python36\python.EXE" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\Ziming Gao\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\Ziming Gao\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\Ziming Gao\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Ziming Gao\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ZIMING~1\AppData\Local\Temp\apm-install-dir-118023-10792-ucb8rn.d37ssgu8fr\node_modules\jupyter-notebook\node_modules\bufferutil
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Python36\python.EXE" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\Ziming Gao\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\Ziming Gao\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\Ziming Gao\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Ziming Gao\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ZIMING~1\AppData\Local\Temp\apm-install-dir-118023-10792-ucb8rn.d37ssgu8fr\node_modules\jupyter-notebook\node_modules\runas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\ZIMING~1\AppData\Local\Temp\apm-install-dir-118023-10792-ucb8rn.d37ssgu8fr\package.json'
npm WARN apm-install-dir-118023-10792-ucb8rn.d37ssgu8fr No description
npm WARN apm-install-dir-118023-10792-ucb8rn.d37ssgu8fr No repository field.
npm WARN apm-install-dir-118023-10792-ucb8rn.d37ssgu8fr No README data
npm WARN apm-install-dir-118023-10792-ucb8rn.d37ssgu8fr No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\jupyter-notebook\node_modules\bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\Ziming Gao\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Ziming Gao\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Ziming Gao\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Ziming Gao\\.atom\\.apmrc" "install" "C:\\Users\\ZIMING~1\\AppData\\Local\\Temp\\d-118023-10792-plvsi0.q865pzaor\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ZIMING~1\AppData\Local\Temp\apm-install-dir-118023-10792-ucb8rn.d37ssgu8fr\npm-debug.log
npm ERR! code 1

**Comment by TomGao2001** [comment]
I have a fresh installation of Python 2.7.14 just minutes ago, and Python 3.6.4 w/ a few packages, numpy, mkl, etc.
