### ISSUE TITLE
Error installing jupyter-notebook through Atom on Windows 10

### ISSUE THREAD

**Issue by DocAlchemy** [jupyter/atom-notebook#78]
Installing “jupyter-notebook@0.0.10” failed.Hide output…

> bufferutil@1.2.1 install C:\****\*****~1\*****\***\**\apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9\node_modules\jupyter-notebook\node_modules\bufferutil
> node-gyp rebuild

C:\****\*****~1\*****\***\**\apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9\node_modules\jupyter-notebook\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\****\*****~1\*****\***\atom\app-1.30.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\****\*****~1\*****\***\atom\app-1.30.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

> utf-8-validate@1.2.2 install C:\****\*****~1\*****\***\Local\Temp\apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9\node_modules\jupyter-notebook\node_modules\utf-8-validate
> node-gyp rebuild

C:\****\*****~1\*****\***\Local\Temp\apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9\node_modules\jupyter-notebook\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\****\*****~1\*****\***\atom\app-1.30.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\****\*****~1\*****\***\\atom\app-1.30.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

> pathwatcher@8.0.2 install C:\****\*****~1\*****\***\Temp\apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9\node_modules\jupyter-notebook\node_modules\pathwatcher
> node-gyp rebuild

C:\****\*****~1\*****\***\Temp\apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9\node_modules\jupyter-notebook\node_modules\pathwatcher>if not defined npm_config_node_gyp (node "C:\****\*****~1\*****\***\atom\app-1.30.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node C:\****\*****~1\*****\***\atom\app-1.30.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\****\*****~1\*****\***\Temp\apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9
`-- (empty)

npm WARN deprecated jupyter-js-services@0.21.1: This package has moved to @jupyterlab/services
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\****\*****~1\*****\***\Python\Python36-32\python.EXE" is v3.6.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\****\*****~1\*****\***\atom\app-1.30.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\****\*****~1\*****\***\atom\app-1.30.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\****\*****~1\*****\***\\atom\\app-1.30.0\\resources\\app\\apm\\bin\\node.exe" "C:\****\*****~1\*****\***\\atom\\app-1.30.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\****\*****~1\*****\***\\apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9\node_modules\jupyter-notebook\node_modules\bufferutil
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\****\*****~1\*****\***\Python\Python36-32\python.EXE" is v3.6.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\****\*****~1\*****\***\atom\app-1.30.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\****\*****~1\*****\***\atom\app-1.30.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\****\*****~1\*****\***\\atom\\app-1.30.0\\resources\\app\\apm\\bin\\node.exe" "C:\****\*****~1\*****\***\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\****\*****~1\*****\***\apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9\node_modules\jupyter-notebook\node_modules\utf-8-validate
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\****\*****~1\*****\***\Python\Python36-32\python.EXE" is v3.6.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\****\*****~1\*****\***\atom\app-1.30.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\****\*****~1\*****\***\atom\app-1.30.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\****\*****~1\*****\***\\atom\\app-1.30.0\\resources\\app\\apm\\bin\\node.exe" "C:\****\*****~1\*****\***\\atom\\app-1.30.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\****\*****~1\*****\***\Temp\apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9\node_modules\jupyter-notebook\node_modules\pathwatcher
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\****\*****~1\*****\***\Temp\apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9\package.json'
npm WARN apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9 No description
npm WARN apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9 No repository field.
npm WARN apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9 No README data
npm WARN apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\jupyter-notebook\node_modules\bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules\jupyter-notebook\node_modules\utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\****\*****~1\*****\***\atom\\app-1.30.0\\resources\\app\\apm\\bin\\node.exe" "C:\****\*****~1\*****\***\\atom\\app-1.30.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\****\*****~1\*****\***\\.atom\\.apm\\.apmrc" "--userconfig" "C:\****\*****~1\*****\***\.atom\\.apmrc" "install" C:\****\*****~1\*****\***\\AppData\\Local\\Temp\\d-118818-10940-2ugg11.c1f3xwp14i\\package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pathwatcher@8.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher@8.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pathwatcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pathwatcher
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pathwatcher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    C:\****\*****~1\*****\***\Temp\apm-install-dir-118818-10940-1kfreaj.fvpu3gcik9\npm-debug.log
npm ERR! code 1

**Comment by gabefair** [comment]
I have the same problem. Windows 10 Pro. Atom version: 1.32.2
