### ISSUE TITLE
Couldn't install the package

### ISSUE THREAD

**Issue by pdshah2** [jupyter/atom-notebook#79]
bufferutil@1.2.1 install /private/var/folders/2q/kpyx42bx6gnc6f3b15rwxzkw0000gn/T/apm-install-dir-118827-56681-1w5mbi1.lejqbyb9/node_modules/jupyter-notebook/node_modules/bufferutil
> node-gyp rebuild

> utf-8-validate@1.2.2 install /private/var/folders/2q/kpyx42bx6gnc6f3b15rwxzkw0000gn/T/apm-install-dir-118827-56681-1w5mbi1.lejqbyb9/node_modules/jupyter-notebook/node_modules/utf-8-validate
> node-gyp rebuild

> pathwatcher@8.0.2 install /private/var/folders/2q/kpyx42bx6gnc6f3b15rwxzkw0000gn/T/apm-install-dir-118827-56681-1w5mbi1.lejqbyb9/node_modules/jupyter-notebook/node_modules/pathwatcher
> node-gyp rebuild

/private/var/folders/2q/kpyx42bx6gnc6f3b15rwxzkw0000gn/T/apm-install-dir-118827-56681-1w5mbi1.lejqbyb9
└── (empty)

npm WARN deprecated jupyter-js-services@0.21.1: This package has moved to @jupyterlab/services
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.5, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/2q/kpyx42bx6gnc6f3b15rwxzkw0000gn/T/apm-install-dir-118827-56681-1w5mbi1.lejqbyb9/node_modules/jupyter-notebook/node_modules/bufferutil
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.5, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/2q/kpyx42bx6gnc6f3b15rwxzkw0000gn/T/apm-install-dir-118827-56681-1w5mbi1.lejqbyb9/node_modules/jupyter-notebook/node_modules/utf-8-validate
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.5, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/2q/kpyx42bx6gnc6f3b15rwxzkw0000gn/T/apm-install-dir-118827-56681-1w5mbi1.lejqbyb9/node_modules/jupyter-notebook/node_modules/pathwatcher
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/2q/kpyx42bx6gnc6f3b15rwxzkw0000gn/T/apm-install-dir-118827-56681-1w5mbi1.lejqbyb9/package.json'
npm WARN apm-install-dir-118827-56681-1w5mbi1.lejqbyb9 No description
npm WARN apm-install-dir-118827-56681-1w5mbi1.lejqbyb9 No repository field.
npm WARN apm-install-dir-118827-56681-1w5mbi1.lejqbyb9 No README data
npm WARN apm-install-dir-118827-56681-1w5mbi1.lejqbyb9 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules/jupyter-notebook/node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules/jupyter-notebook/node_modules/utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Darwin 17.7.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/parth/.atom/.apm/.apmrc" "--userconfig" "/Users/parth/.atom/.apmrc" "install" "/private/var/folders/2q/kpyx42bx6gnc6f3b15rwxzkw0000gn/T/d-118827-56681-md1i99.ocix8q6w29/package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pathwatcher@8.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher@8.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pathwatcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pathwatcher
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pathwatcher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/2q/kpyx42bx6gnc6f3b15rwxzkw0000gn/T/apm-install-dir-118827-56681-1w5mbi1.lejqbyb9/npm-debug.log
npm ERR! code 1

**Comment by 2Max4** [comment]
Got exactly the same issue! Has anyone found a workaround jet?

**Comment by harrisonford** [comment]
So... Dead repo? Not much activity going on it seems.
