### ISSUE TITLE
"Failed to load the jupyter-notebook package" on Atom 1.1.0

### ISSUE THREAD

**Issue by gnestor** [jupyter/atom-notebook#8]
[Enter steps to reproduce below:]

1. `apm install`
2. Run Atom (1.1.0)

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [jupyter-notebook](https://github.com/willwhitney/jupyter-notebook-atom) package, v0.0.1

### Stack Trace

Failed to load the jupyter-notebook package

```
At Could not locate the bindings file. Tried:
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/build/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/build/Debug/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/build/Release/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/out/Debug/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/Debug/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/out/Release/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/Release/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/build/default/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/compiled/2.3.1/darwin/x64/zmq.node

Error: Could not locate the bindings file. Tried:
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/build/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/build/Debug/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/build/Release/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/out/Debug/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/Debug/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/out/Release/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/Release/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/build/default/zmq.node
 → /Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/compiled/2.3.1/darwin/x64/zmq.node
    at bindings (/Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/grant/Downloads/atom-notebook/node_modules/jupyter-kernel-launcher/node_modules/jmp/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:428:26)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "native-ui",
      "atom-toychest"
    ],
    "disabledPackages": [
      "RubyMotion",
      "atom-ternjs",
      "preview",
      "SFTP-deployment",
      "language-haml"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Stylus, v1.2.1
api-workbench, v0.8.6
atom-toychest, v0.3.0
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
file-icons, v1.6.11
jupyter-notebook, v0.0.1
language-ejs, v0.2.0
language-gradle, v0.0.3
language-jade, v0.6.2
linter, v1.11.2
linter-eslint, v5.2.1
linter-htmlhint, v0.2.1
linter-sass-lint, v0.4.1
native-ui, v0.8.4
open-recent, v4.0.1
pigments, v0.19.0
pretty-json, v0.4.1
react, v0.12.10
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by gnestor** [comment]
I was able to install atom-notebook doing the following:

1. Clone the repo and `npm install` or `apm install` (using Node 0.10.36)
2. `apm link`
3. Running Atom 1.1.0
4. Rebuilding packages in Atom after being prompted to by the Incompatible Packages service
5. Relaunching Atom

I have confirmed that pathwatcher@4.4.3 (which depends on runas) fails to build on Node >=4 (which is used by Atom >=1.2). The current version of pathwatcher is 6.3.0 and it builds fine on Node >=4. So simply bumping the version of pathwatcher to 6.3.0 in package.json fixes the build bug for pathwatcher and runas.

There is still an issue with atom-notebook's dependency on zmq and its dependency on bindings which is causing it fail on launch. See: https://github.com/jupyter/atom-notebook/issues/9
