### ISSUE TITLE
can't install this package

### ISSUE THREAD

**Issue by Aithosa** [jupyter/atom-notebook#80]
when i click install button in atom it always show 'Installing “jupyter-notebook@0.0.10” failed.Show output…' message. while other packages can install normally. 

i known another way to install package by "Installing “apm install jupyter-notebook", but i don't know why i  don't have apm commend in my windows system while i install atom by binary file and never do anything during installing.

**Comment by bhaveshthaker** [comment]
Win 10 64 bit - other packages are getting installed correctly. Getting following error:

`
Installing “jupyter-notebook@0.0.10” failed.Hide output…

> bufferutil@1.2.1 install C:\Users\BT0053~1\AppData\Local\Temp\apm-install-dir-1181018-14780-53j55x.bbx6o\node_modules\jupyter-notebook\node_modules\bufferutil
> node-gyp rebuild


(base) C:\Users\BT0053~1\AppData\Local\Temp\apm-install-dir-1181018-14780-53j55x.bbx6o\node_modules\jupyter-notebook\node_modules\bufferutil>if not defined npm_config_node_gyp (node "D:\Apps\Atom x64\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Apps\Atom x64\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

> utf-8-validate@1.2.2 install C:\Users\BT0053~1\AppData\Local\Temp\apm-install-dir-1181018-14780-53j55x.bbx6o\node_modules\jupyter-notebook\node_modules\utf-8-validate
> node-gyp rebuild


(base) C:\Users\BT0053~1\AppData\Local\Temp\apm-install-dir-1181018-14780-53j55x.bbx6o\node_modules\jupyter-notebook\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "D:\Apps\Atom x64\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Apps\Atom x64\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

> pathwatcher@8.0.2 install C:\Users\BT0053~1\AppData\Local\Temp\apm-install-dir-1181018-14780-53j55x.bbx6o\node_modules\jupyter-notebook\node_modules\pathwatcher
> node-gyp rebuild


(base) C:\Users\BT0053~1\AppData\Local\Temp\apm-install-dir-1181018-14780-53j55x.bbx6o\node_modules\jupyter-notebook\node_modules\pathwatcher>if not defined npm_config_node_gyp (node "D:\Apps\Atom x64\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Apps\Atom x64\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

npm WARN deprecated jupyter-js-services@0.21.1: This package has moved to @jupyterlab/services
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
gyp info it worked if it ends with ok
gyp verb cli [ 'D:\\Apps\\Atom x64\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'D:\\Apps\\Atom x64\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\ProgramData\Anaconda3\python.EXE
gyp verb check python version `C:\ProgramData\Anaconda3\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.4\r\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\ProgramData\Anaconda3\python.EXE" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (D:\Apps\Atom x64\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at D:\Apps\Atom x64\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\Apps\\Atom x64\\resources\\app\\apm\\bin\\node.exe" "D:\\Apps\\Atom x64\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\BT0053~1\AppData\Local\Temp\apm-install-dir-1181018-14780-53j55x.bbx6o\node_modules\jupyter-notebook\node_modules\bufferutil
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp info it worked if it ends with ok
gyp verb cli [ 'D:\\Apps\\Atom x64\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'D:\\Apps\\Atom x64\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\ProgramData\Anaconda3\python.EXE
gyp verb check python version `C:\ProgramData\Anaconda3\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.4\r\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\ProgramData\Anaconda3\python.EXE" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (D:\Apps\Atom x64\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at D:\Apps\Atom x64\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\Apps\\Atom x64\\resources\\app\\apm\\bin\\node.exe" "D:\\Apps\\Atom x64\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\BT0053~1\AppData\Local\Temp\apm-install-dir-1181018-14780-53j55x.bbx6o\node_modules\jupyter-notebook\node_modules\utf-8-validate
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp info it worked if it ends with ok
gyp verb cli [ 'D:\\Apps\\Atom x64\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'D:\\Apps\\Atom x64\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Apps\Atom x64\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\ProgramData\Anaconda3\python.EXE
gyp verb check python version `C:\ProgramData\Anaconda3\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.4\r\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\ProgramData\Anaconda3\python.EXE" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (D:\Apps\Atom x64\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at D:\Apps\Atom x64\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\Apps\\Atom x64\\resources\\app\\apm\\bin\\node.exe" "D:\\Apps\\Atom x64\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\BT0053~1\AppData\Local\Temp\apm-install-dir-1181018-14780-53j55x.bbx6o\node_modules\jupyter-notebook\node_modules\pathwatcher
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\BT0053~1\AppData\Local\Temp\apm-install-dir-1181018-14780-53j55x.bbx6o\package.json'
npm WARN apm-install-dir-1181018-14780-53j55x.bbx6o No description
npm WARN apm-install-dir-1181018-14780-53j55x.bbx6o No repository field.
npm WARN apm-install-dir-1181018-14780-53j55x.bbx6o No README data
npm WARN apm-install-dir-1181018-14780-53j55x.bbx6o No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\jupyter-notebook\node_modules\bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules\jupyter-notebook\node_modules\utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pathwatcher@8.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher@8.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bt0053987ipc\.atom\.apm\_logs\2018-11-18T11_50_07_389Z-debug.log
`
