### ISSUE TITLE
Can't install package 

### ISSUE THREAD

**Issue by Valensic** [jupyter/atom-notebook#81]
I'd really like to use this package but my installation fails

OS: Mac OS 10.13
Python 3.6.5

> bufferutil@1.2.1 install /private/var/folders/jw/yddzh5hs7nd1tm2cd111vb8c0000gn/T/apm-install-dir-118912-1056-fng4rl.wshb5/node_modules/jupyter-notebook/node_modules/bufferutil
> node-gyp rebuild

> utf-8-validate@1.2.2 install /private/var/folders/jw/yddzh5hs7nd1tm2cd111vb8c0000gn/T/apm-install-dir-118912-1056-fng4rl.wshb5/node_modules/jupyter-notebook/node_modules/utf-8-validate
> node-gyp rebuild

> pathwatcher@8.0.2 install /private/var/folders/jw/yddzh5hs7nd1tm2cd111vb8c0000gn/T/apm-install-dir-118912-1056-fng4rl.wshb5/node_modules/jupyter-notebook/node_modules/pathwatcher
> node-gyp rebuild

npm WARN deprecated jupyter-js-services@0.21.1: This package has moved to @jupyterlab/services
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
gyp info it worked if it ends with ok
gyp verb cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
gyp verb cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" in the PATH
gyp verb `which` succeeded /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh
gyp verb check python version `/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh -c "import platform; print(platform.python_version());"` returned: "3.6.5\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.5, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/jw/yddzh5hs7nd1tm2cd111vb8c0000gn/T/apm-install-dir-118912-1056-fng4rl.wshb5/node_modules/jupyter-notebook/node_modules/bufferutil
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp info it worked if it ends with ok
gyp verb cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
gyp verb cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" in the PATH
gyp verb `which` succeeded /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh
gyp verb check python version `/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh -c "import platform; print(platform.python_version());"` returned: "3.6.5\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.5, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/jw/yddzh5hs7nd1tm2cd111vb8c0000gn/T/apm-install-dir-118912-1056-fng4rl.wshb5/node_modules/jupyter-notebook/node_modules/utf-8-validate
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp info it worked if it ends with ok
gyp verb cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
gyp verb cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" in the PATH
gyp verb `which` succeeded /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh
gyp verb check python version `/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh -c "import platform; print(platform.python_version());"` returned: "3.6.5\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.5, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/jw/yddzh5hs7nd1tm2cd111vb8c0000gn/T/apm-install-dir-118912-1056-fng4rl.wshb5/node_modules/jupyter-notebook/node_modules/pathwatcher
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/jw/yddzh5hs7nd1tm2cd111vb8c0000gn/T/apm-install-dir-118912-1056-fng4rl.wshb5/package.json'

npm WARN apm-install-dir-118912-1056-fng4rl.wshb5 No description
npm WARN apm-install-dir-118912-1056-fng4rl.wshb5 No repository field.
npm WARN apm-install-dir-118912-1056-fng4rl.wshb5 No README data
npm WARN apm-install-dir-118912-1056-fng4rl.wshb5 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules/jupyter-notebook/node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules/jupyter-notebook/node_modules/utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pathwatcher@8.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher@8.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/carlovalensise/.atom/.apm/_logs/2018-10-12T15_48_04_816Z-debug.log

**Comment by thebilly31** [comment]
Did you find a solution? I am currently running into the same problem...

**Comment by Valensic** [comment]
Actually no , sometimes I try again without results

**Comment by harrisonford** [comment]
Same problem here, rip Atom.

**Comment by egarciamartin** [comment]
Same problem here. No solution?
