### ISSUE TITLE
Installing “jupyter-notebook@0.0.10” failed - (windows 10) Atom 1.32.2

### ISSUE THREAD

**Issue by FoFo-FoSho** [jupyter/atom-notebook#85]
Hi there =)

Below is the error that was produced when trying to install Juypter package on Atom - below that are my computer specs. Any help would be greatly appreciated. 

Atom version: 1.32.2 

#####################

> bufferutil@1.2.1 install C:\Users\chris\AppData\Local\Temp\apm-install-dir-1181130-2104-wo1nub.wbcpb\node_modules\jupyter-notebook\node_modules\bufferutil
> node-gyp rebuild

(py37) C:\Users\chris\AppData\Local\Temp\apm-install-dir-1181130-2104-wo1nub.wbcpb\node_modules\jupyter-notebook\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

> utf-8-validate@1.2.2 install C:\Users\chris\AppData\Local\Temp\apm-install-dir-1181130-2104-wo1nub.wbcpb\node_modules\jupyter-notebook\node_modules\utf-8-validate
> node-gyp rebuild

(py37) C:\Users\chris\AppData\Local\Temp\apm-install-dir-1181130-2104-wo1nub.wbcpb\node_modules\jupyter-notebook\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

> pathwatcher@8.0.2 install C:\Users\chris\AppData\Local\Temp\apm-install-dir-1181130-2104-wo1nub.wbcpb\node_modules\jupyter-notebook\node_modules\pathwatcher
> node-gyp rebuild

(py37) C:\Users\chris\AppData\Local\Temp\apm-install-dir-1181130-2104-wo1nub.wbcpb\node_modules\jupyter-notebook\node_modules\pathwatcher>if not defined npm_config_node_gyp (node "C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

npm WARN deprecated jupyter-js-services@0.21.1: This package has moved to @jupyterlab/services
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\chris\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'C:\\Users\\chris\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\chris\Anaconda3\envs\py37\python.EXE
gyp verb check python version `C:\Users\chris\Anaconda3\envs\py37\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.7.1\r\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\chris\Anaconda3\envs\py37\python.EXE" is v3.7.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\chris\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\chris\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\chris\AppData\Local\Temp\apm-install-dir-1181130-2104-wo1nub.wbcpb\node_modules\jupyter-notebook\node_modules\bufferutil
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\chris\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'C:\\Users\\chris\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\chris\Anaconda3\envs\py37\python.EXE
gyp verb check python version `C:\Users\chris\Anaconda3\envs\py37\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.7.1\r\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\chris\Anaconda3\envs\py37\python.EXE" is v3.7.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\chris\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\chris\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\chris\AppData\Local\Temp\apm-install-dir-1181130-2104-wo1nub.wbcpb\node_modules\jupyter-notebook\node_modules\utf-8-validate
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\chris\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'C:\\Users\\chris\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\chris\Anaconda3\envs\py37\python.EXE
gyp verb check python version `C:\Users\chris\Anaconda3\envs\py37\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.7.1\r\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\chris\Anaconda3\envs\py37\python.EXE" is v3.7.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\chris\AppData\Local\atom\app-1.32.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\chris\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\chris\\AppData\\Local\\atom\\app-1.32.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\chris\AppData\Local\Temp\apm-install-dir-1181130-2104-wo1nub.wbcpb\node_modules\jupyter-notebook\node_modules\pathwatcher
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\chris\AppData\Local\Temp\apm-install-dir-1181130-2104-wo1nub.wbcpb\package.json'
npm WARN apm-install-dir-1181130-2104-wo1nub.wbcpb No description
npm WARN apm-install-dir-1181130-2104-wo1nub.wbcpb No repository field.
npm WARN apm-install-dir-1181130-2104-wo1nub.wbcpb No README data
npm WARN apm-install-dir-1181130-2104-wo1nub.wbcpb No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\jupyter-notebook\node_modules\bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules\jupyter-notebook\node_modules\utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pathwatcher@8.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher@8.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chris\.atom\.apm\_logs\2018-12-30T09_29_14_722Z-debug.log

#######################

 Operating System: Windows 10 Pro 64-bit (10.0, Build 17134) (17134.rs4_release.180410-1804)
                 Language: English (Regional Setting: English)
      System Manufacturer: Microsoft Corporation
             System Model: Surface Pro 4
                     BIOS: 108.2318.769 (type: UEFI)
                Processor: Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 CPUs), ~2.2GHz
                   Memory: 8192MB RAM
      Available OS Memory: 8118MB RAM
                Page File: 12769MB used, 3028MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 192 DPI (200 percent)
       System DPI Setting: 192 DPI (200 percent)
          DWM DPI Scaling: UnKnown
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.17134.0001 64bit Unicode

**Comment by mroettgen** [comment]
Affects me, too.

**Comment by laurivaltteri** [comment]
Here as well

**Comment by ChrisHastieIW** [comment]
And here

**Comment by lyons7** [comment]
Same -- it says that this is deprecated, does that mean it's been abandoned? I hope not, because this would be a great functionality (I know there's nteract, but I'm not that excited, I just want to open ipynb files and edit them in Atom is that too much to ask?!)

**Comment by nakulstar95** [comment]
here as well

**Comment by Irfan-X** [comment]
and here

**Comment by henryxparker** [comment]
and here

**Comment by GurayKilinc** [comment]
and heree

**Comment by cdedonno** [comment]
here too

**Comment by nosratullah** [comment]
me too!

**Comment by varungujarathi9** [comment]
same here

**Comment by Minjeong-Song** [comment]
Same here

**Comment by ch3pasov** [comment]
#metoo
