### ISSUE TITLE
Installation fails (Ubuntu 18.10)

### ISSUE THREAD

**Issue by kr4in** [jupyter/atom-notebook#87]
Stack trace:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Ubuntu 18.10
**Thrown From**: [jupyter-notebook](https://github.com/jupyter/atom-notebook) package 0.0.10

### Stack Trace

Failed to load the jupyter-notebook package

```
At /home/**/.atom/packages/jupyter-notebook/lib/main.js: Unexpected token (36:4)

SyntaxError: /home/**/.atom/packages/jupyter-notebook/lib/main.js: Unexpected token (36:4)
        return el;
      }
    });
  },

  deactivate() {
    at Parser.pp.raise (/app.asar/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/app.asar/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.expect (/app.asar/node_modules/babylon/lib/parser/util.js:76:33)
    at Parser.pp.parseExprList (/app.asar/node_modules/babylon/lib/parser/expression.js:785:12)
    at Parser.pp.parseSubscripts (/app.asar/node_modules/babylon/lib/parser/expression.js:270:29)
    at Parser.pp.parseExprSubscripts (/app.asar/node_modules/babylon/lib/parser/expression.js:240:17)
    at Parser.pp.parseMaybeUnary (/app.asar/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/app.asar/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/app.asar/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/app.asar/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExpression (/app.asar/node_modules/babylon/lib/parser/expression.js:79:19)
    at Parser.pp.parseStatement (/app.asar/node_modules/babylon/lib/parser/statement.js:137:23)
    at Parser.parseStatement (/app.asar/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseBlock (/app.asar/node_modules/babylon/lib/parser/statement.js:442:21)
    at Parser.pp.parseFunctionBody (/app.asar/node_modules/babylon/lib/parser/expression.js:747:22)
    at Parser.parseFunctionBody (/app.asar/node_modules/babylon/lib/plugins/flow.js:643:20)
    at Parser.pp.parseMethod (/app.asar/node_modules/babylon/lib/parser/expression.js:717:8)
    at Parser.pp.parseObjPropValue (/app.asar/node_modules/babylon/lib/parser/expression.js:658:23)
    at Parser.parseObjPropValue (/app.asar/node_modules/babylon/lib/plugins/flow.js:891:13)
    at Parser.pp.parseObj (/app.asar/node_modules/babylon/lib/parser/expression.js:640:10)
    at Parser.pp.parseExprAtom (/app.asar/node_modules/babylon/lib/parser/expression.js:392:19)
    at Parser.parseExprAtom (/app.asar/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/app.asar/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/app.asar/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/app.asar/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/app.asar/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/app.asar/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExport (/app.asar/node_modules/babylon/lib/parser/statement.js:682:21)
    at Parser.parseExport (/app.asar/node_modules/babylon/lib/plugins/flow.js:713:20)
    at Parser.pp.parseStatement (/app.asar/node_modules/babylon/lib/parser/statement.js:115:90)
    at Parser.parseStatement (/app.asar/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseTopLevel (/app.asar/node_modules/babylon/lib/parser/statement.js:30:21)
    at Parser.parse (/app.asar/node_modules/babylon/lib/parser/index.js:70:17)
    at Object.parse (/app.asar/node_modules/babylon/lib/index.js:45:50)
    at Object.exports.default (/app.asar/node_modules/babel-core/lib/helpers/parse.js:36:18)
    at File.parse (/app.asar/node_modules/babel-core/lib/transformation/file/index.js:574:40)
    at File.parseCode (/app.asar/node_modules/babel-core/lib/transformation/file/index.js:691:20)
    at /app.asar/node_modules/babel-core/lib/transformation/pipeline.js:167:12
    at File.wrap (/app.asar/node_modules/babel-core/lib/transformation/file/index.js:639:16)
    at Pipeline.transform (/app.asar/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
    at Object.e.compile (/usr/share/atom/resources/app/static/<embedded>:11:576862)
    at Object.compile (/usr/share/atom/resources/app/static/<embedded>:11:573661)
    at compileFileAtPath (/usr/share/atom/resources/app/static/<embedded>:11:147800)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150197)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:639511)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:2932767)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:2919478)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:2918310)
    at Package.load (/usr/share/atom/resources/app/static/<embedded>:11:2919051)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/static/<embedded>:11:381323)
    at PackageManager.loadPackage (/usr/share/atom/resources/app/static/<embedded>:11:380051)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382555)
    at /usr/share/atom/resources/app/static/<embedded>:11:917000
    at r (/usr/share/atom/resources/app/static/<embedded>:11:911606)
    at o (/usr/share/atom/resources/app/static/<embedded>:14:1037724)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1037878)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1036480)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -4:24.5.0 core:move-up (input.hidden-input)
     -4:24.3.0 editor:newline (input.hidden-input)
     -4:23.1.0 core:backspace (input.hidden-input)
     -4:21.2.0 core:move-down (input.hidden-input)
     -4:20.9.0 editor:newline (input.hidden-input)
 25x -4:15.6.0 core:backspace (input.hidden-input)
     -4:10.7.0 editor:newline (input.hidden-input)
  3x -4:09.5.0 core:backspace (input.hidden-input)
  2x -4:05.2.0 editor:newline (input.hidden-input)
  3x -3:35.3.0 core:backspace (input.hidden-input)
  2x -3:25.4.0 editor:newline (input.hidden-input)
     -3:21.5.0 intentions:highlight (input.hidden-input)
     -3:21.4.0 core:save (input.hidden-input)
     -2:59.6.0 key-binding-resolver:toggle (div.tool-panel.tree-view)
     -2:59.4.0 settings-view:open (div.tool-panel.tree-view)
     -2:57.9.0 key-binding-resolver:toggle (div.panels-item)
```

### Non-Core Packages

```
busy-signal 2.0.0 
file-icons 2.1.30 
ide-python 1.4.0 
intentions 1.1.5 
jupyter-notebook 0.0.10 
language-dotenv 1.2.0 
language-ejs 0.4.0 
language-gitignore 0.3.0 
language-javascript-jsx 0.3.7 
linter 2.3.0 
linter-eslint 8.5.2 
linter-ui-default 1.7.1 
pdf-view 0.71.0 
react 0.18.0 
remote-ftp 2.2.2 
```

**Comment by adipalihovici** [comment]
You can fix the error but unfortunately the layout of the notebook will become messed up. See here: https://github.com/jupyter/atom-notebook/issues/67#

**Comment by kr4in** [comment]
Thank you! Looks like sticking with Hydrogen or just plain old Jupyter Lab is the way to gain. Thanks for your help.
