### ISSUE TITLE
getting an error when install jupyter-notebook on Atom

### ISSUE THREAD

**Issue by omarHazim** [jupyter/atom-notebook#89]
Installing “jupyter-notebook@0.0.10” failed.Hide output…

> bufferutil@1.2.1 install /private/var/folders/_v/kvyt0_092q7_d8k2zvyl7f900000gn/T/apm-install-dir-11973-954-1cmsoui.yd7j/node_modules/jupyter-notebook/node_modules/bufferutil
> node-gyp rebuild

> utf-8-validate@1.2.2 install /private/var/folders/_v/kvyt0_092q7_d8k2zvyl7f900000gn/T/apm-install-dir-11973-954-1cmsoui.yd7j/node_modules/jupyter-notebook/node_modules/utf-8-validate
> node-gyp rebuild

> pathwatcher@8.1.0 install /private/var/folders/_v/kvyt0_092q7_d8k2zvyl7f900000gn/T/apm-install-dir-11973-954-1cmsoui.yd7j/node_modules/jupyter-notebook/node_modules/pathwatcher
> node-gyp rebuild

npm WARN deprecated jupyter-js-services@0.21.1: This package has moved to @jupyterlab/services
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.6, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/_v/kvyt0_092q7_d8k2zvyl7f900000gn/T/apm-install-dir-11973-954-1cmsoui.yd7j/node_modules/jupyter-notebook/node_modules/bufferutil
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.6, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/_v/kvyt0_092q7_d8k2zvyl7f900000gn/T/apm-install-dir-11973-954-1cmsoui.yd7j/node_modules/jupyter-notebook/node_modules/utf-8-validate
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.6, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/omar/Desktop/apps/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/_v/kvyt0_092q7_d8k2zvyl7f900000gn/T/apm-install-dir-11973-954-1cmsoui.yd7j/node_modules/jupyter-notebook/node_modules/pathwatcher
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/_v/kvyt0_092q7_d8k2zvyl7f900000gn/T/apm-install-dir-11973-954-1cmsoui.yd7j/package.json'
npm WARN apm-install-dir-11973-954-1cmsoui.yd7j No description
npm WARN apm-install-dir-11973-954-1cmsoui.yd7j No repository field.
npm WARN apm-install-dir-11973-954-1cmsoui.yd7j No README data
npm WARN apm-install-dir-11973-954-1cmsoui.yd7j No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules/jupyter-notebook/node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules/jupyter-notebook/node_modules/utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pathwatcher@8.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher@8.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/omar/.atom/.apm/_logs/2019-08-03T21_08_01_643Z-debug.log

**Comment by brando90** [comment]
I am getting the following error:

```
Installing “jupyter-notebook@0.0.10” failed.Hide output…

> bufferutil@1.2.1 install /private/var/folders/vz/9vkmdqbn3ml_12rcbh66rn4c0000gn/T/apm-install-dir-11977-7707-1q9w5op.i7nh/node_modules/jupyter-notebook/node_modules/bufferutil
> node-gyp rebuild


> utf-8-validate@1.2.2 install /private/var/folders/vz/9vkmdqbn3ml_12rcbh66rn4c0000gn/T/apm-install-dir-11977-7707-1q9w5op.i7nh/node_modules/jupyter-notebook/node_modules/utf-8-validate
> node-gyp rebuild


> pathwatcher@8.1.0 install /private/var/folders/vz/9vkmdqbn3ml_12rcbh66rn4c0000gn/T/apm-install-dir-11977-7707-1q9w5op.i7nh/node_modules/jupyter-notebook/node_modules/pathwatcher
> node-gyp rebuild


npm WARN deprecated jupyter-js-services@0.21.1: This package has moved to @jupyterlab/services
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
gyp info it worked if it ends with ok
gyp verb cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
gyp verb cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" in the PATH
gyp verb `which` succeeded /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh
gyp verb check python version `/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh -c "import platform; print(platform.python_version());"` returned: "3.7.3\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/vz/9vkmdqbn3ml_12rcbh66rn4c0000gn/T/apm-install-dir-11977-7707-1q9w5op.i7nh/node_modules/jupyter-notebook/node_modules/bufferutil
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp info it worked if it ends with ok
gyp verb cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
gyp verb cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" in the PATH
gyp verb `which` succeeded /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh
gyp verb check python version `/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh -c "import platform; print(platform.python_version());"` returned: "3.7.3\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/vz/9vkmdqbn3ml_12rcbh66rn4c0000gn/T/apm-install-dir-11977-7707-1q9w5op.i7nh/node_modules/jupyter-notebook/node_modules/utf-8-validate
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp info it worked if it ends with ok
gyp verb cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
gyp verb cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" in the PATH
gyp verb `which` succeeded /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh /Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh
gyp verb check python version `/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh -c "import platform; print(platform.python_version());"` returned: "3.7.3\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/vz/9vkmdqbn3ml_12rcbh66rn4c0000gn/T/apm-install-dir-11977-7707-1q9w5op.i7nh/node_modules/jupyter-notebook/node_modules/pathwatcher
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/vz/9vkmdqbn3ml_12rcbh66rn4c0000gn/T/apm-install-dir-11977-7707-1q9w5op.i7nh/package.json'
npm WARN apm-install-dir-11977-7707-1q9w5op.i7nh No description
npm WARN apm-install-dir-11977-7707-1q9w5op.i7nh No repository field.
npm WARN apm-install-dir-11977-7707-1q9w5op.i7nh No README data
npm WARN apm-install-dir-11977-7707-1q9w5op.i7nh No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules/jupyter-notebook/node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules/jupyter-notebook/node_modules/utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pathwatcher@8.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher@8.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brandomiranda/.atom/.apm/_logs/2019-08-07T16_53_46_452Z-debug.log

```

**Comment by brando90** [comment]
made this discussion: https://discuss.atom.io/t/how-to-install-jupyter-notebook-reader-in-atom/67426
