### ISSUE TITLE
Uncaught TypeError: msg.text.join is not a function

### ISSUE THREAD

**Issue by Euniceisnice** [jupyter/atom-notebook#92]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [jupyter-notebook](https://github.com/jupyter/atom-notebook) package 0.0.10

### Stack Trace

Uncaught TypeError: msg.text.join is not a function

```
At /Users/euniceng/.atom/packages/jupyter-notebook/lib/display-area.js:68

TypeError: msg.text.join is not a function
    at DisplayArea.makeMimeBundle (/packages/jupyter-notebook/lib/display-area.js:68:39)
    at /packages/jupyter-notebook/lib/display-area.js:49:31
    at Array.map (<anonymous>)
    at DisplayArea.transformMimeBundle (/packages/jupyter-notebook/lib/display-area.js:48:55)
    at DisplayArea.componentWillMount (/packages/jupyter-notebook/lib/display-area.js:29:10)
    at ReactCompositeComponentWrapper.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactCompositeComponent.js:210:12)
    at Object.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.mountChildren (/packages/jupyter-notebook/node_modules/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent._createContentMarkup (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:591:32)
    at ReactDOMComponent.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:479:29)
    at Object.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.mountChildren (/packages/jupyter-notebook/node_modules/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent._createContentMarkup (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:591:32)
    at ReactDOMComponent.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:479:29)
    at Object.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactCompositeComponentWrapper.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactCompositeComponent.js:225:34)
    at Object.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.mountChildren (/packages/jupyter-notebook/node_modules/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent._createContentMarkup (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:591:32)
    at ReactDOMComponent.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:479:29)
    at Object.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.mountChildren (/packages/jupyter-notebook/node_modules/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent._createContentMarkup (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:591:32)
    at ReactDOMComponent.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:479:29)
    at Object.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.mountChildren (/packages/jupyter-notebook/node_modules/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent._createContentMarkup (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:591:32)
    at ReactDOMComponent.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:479:29)
    at Object.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactCompositeComponentWrapper.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactCompositeComponent.js:225:34)
```

### Commands

```
```

### Non-Core Packages

```
atom-runner 2.7.1 
Hydrogen 2.13.1 
ide-json 0.2.1 
jupyter-notebook 0.0.10 
script 3.18.1 
```

**Comment by miftanurfarid** [comment]
> I tried the solution here #67
> (remove the curly bracket)
> and it turned out like this 
> 
> **Atom**: 1.40.1 x64
> **Electron**: 3.1.10
> **OS**: Mac OS X 10.14.6
> **Thrown From**: [jupyter-notebook](https://github.com/jupyter/atom-notebook) package 0.0.10
> 
> ### Stack Trace
> Uncaught TypeError: msg.text.join is not a function
> 
> ```
> At /Users/euniceng/.atom/packages/jupyter-notebook/lib/display-area.js:68
> 
> TypeError: msg.text.join is not a function
>     at DisplayArea.makeMimeBundle (/packages/jupyter-notebook/lib/display-area.js:68:39)
>     at /packages/jupyter-notebook/lib/display-area.js:49:31
>     at Array.map (<anonymous>)
>     at DisplayArea.transformMimeBundle (/packages/jupyter-notebook/lib/display-area.js:48:55)
>     at DisplayArea.componentWillMount (/packages/jupyter-notebook/lib/display-area.js:29:10)
>     at ReactCompositeComponentWrapper.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactCompositeComponent.js:210:12)
>     at Object.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactReconciler.js:37:35)
>     at ReactDOMComponent.mountChildren (/packages/jupyter-notebook/node_modules/react/lib/ReactMultiChild.js:241:44)
>     at ReactDOMComponent._createContentMarkup (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:591:32)
>     at ReactDOMComponent.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:479:29)
>     at Object.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactReconciler.js:37:35)
>     at ReactDOMComponent.mountChildren (/packages/jupyter-notebook/node_modules/react/lib/ReactMultiChild.js:241:44)
>     at ReactDOMComponent._createContentMarkup (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:591:32)
>     at ReactDOMComponent.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:479:29)
>     at Object.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactReconciler.js:37:35)
>     at ReactCompositeComponentWrapper.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactCompositeComponent.js:225:34)
>     at Object.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactReconciler.js:37:35)
>     at ReactDOMComponent.mountChildren (/packages/jupyter-notebook/node_modules/react/lib/ReactMultiChild.js:241:44)
>     at ReactDOMComponent._createContentMarkup (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:591:32)
>     at ReactDOMComponent.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:479:29)
>     at Object.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactReconciler.js:37:35)
>     at ReactDOMComponent.mountChildren (/packages/jupyter-notebook/node_modules/react/lib/ReactMultiChild.js:241:44)
>     at ReactDOMComponent._createContentMarkup (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:591:32)
>     at ReactDOMComponent.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:479:29)
>     at Object.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactReconciler.js:37:35)
>     at ReactDOMComponent.mountChildren (/packages/jupyter-notebook/node_modules/react/lib/ReactMultiChild.js:241:44)
>     at ReactDOMComponent._createContentMarkup (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:591:32)
>     at ReactDOMComponent.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactDOMComponent.js:479:29)
>     at Object.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactReconciler.js:37:35)
>     at ReactCompositeComponentWrapper.mountComponent (/packages/jupyter-notebook/node_modules/react/lib/ReactCompositeComponent.js:225:34)
> ```
> 
> ### Commands
> ### Non-Core Packages
> ```
> atom-runner 2.7.1 
> Hydrogen 2.13.1 
> ide-json 0.2.1 
> jupyter-notebook 0.0.10 
> script 3.18.1 
> ```

change this
`bundle = {'text/plain': msg.text.join('')};`
into this
`bundle = {'jupyter/stream': msg};`
